package ht.ihsi.rgph.mobile.backend.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ht.ihsi.rgph.mobile.backend.entities.Deces;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "tbl_deces".
*/
public class DecesDao extends AbstractDao<Deces, Long> {

    public static final String TABLENAME = "tbl_deces";

    /**
     * Properties of entity Deces.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property DecesId = new Property(0, Long.class, "decesId", true, "decesId");
        public final static Property MenageId = new Property(1, Long.class, "menageId", false, "menageId");
        public final static Property LogeId = new Property(2, Long.class, "logeId", false, "logeId");
        public final static Property BatimentId = new Property(3, Long.class, "batimentId", false, "batimentId");
        public final static Property SdeId = new Property(4, String.class, "sdeId", false, "sdeId");
        public final static Property Qd2NoOrdre = new Property(5, Short.class, "qd2NoOrdre", false, "qd2NoOrdre");
        public final static Property Qd2aSexe = new Property(6, Short.class, "qd2aSexe", false, "qd2aSexe");
        public final static Property Qd2bAgeDecede = new Property(7, String.class, "qd2bAgeDecede", false, "qd2bAgeDecede");
        public final static Property Qd2c1CirconstanceDeces = new Property(8, Short.class, "qd2c1CirconstanceDeces", false, "qd2c1CirconstanceDeces");
        public final static Property Qd2c2CauseDeces = new Property(9, Short.class, "qd2c2CauseDeces", false, "qd2c2CauseDeces");
        public final static Property Statut = new Property(10, Short.class, "statut", false, "statut");
        public final static Property IsFieldAllFilled = new Property(11, Boolean.class, "isFieldAllFilled", false, "isFieldAllFilled");
        public final static Property DateDebutCollecte = new Property(12, String.class, "dateDebutCollecte", false, "dateDebutCollecte");
        public final static Property DateFinCollecte = new Property(13, String.class, "dateFinCollecte", false, "dateFinCollecte");
        public final static Property DureeSaisie = new Property(14, Integer.class, "dureeSaisie", false, "dureeSaisie");
        public final static Property IsContreEnqueteMade = new Property(15, Boolean.class, "isContreEnqueteMade", false, "isContreEnqueteMade");
        public final static Property CodeAgentRecenceur = new Property(16, String.class, "codeAgentRecenceur", false, "codeAgentRecenceur");
        public final static Property IsVerified = new Property(17, Boolean.class, "isVerified", false, "isVerified");
    };


    public DecesDao(DaoConfig config) {
        super(config);
    }
    
    public DecesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"tbl_deces\" (" + //
                "\"decesId\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: decesId
                "\"menageId\" INTEGER," + // 1: menageId
                "\"logeId\" INTEGER," + // 2: logeId
                "\"batimentId\" INTEGER," + // 3: batimentId
                "\"sdeId\" TEXT," + // 4: sdeId
                "\"qd2NoOrdre\" INTEGER," + // 5: qd2NoOrdre
                "\"qd2aSexe\" INTEGER," + // 6: qd2aSexe
                "\"qd2bAgeDecede\" TEXT," + // 7: qd2bAgeDecede
                "\"qd2c1CirconstanceDeces\" INTEGER," + // 8: qd2c1CirconstanceDeces
                "\"qd2c2CauseDeces\" INTEGER," + // 9: qd2c2CauseDeces
                "\"statut\" INTEGER," + // 10: statut
                "\"isFieldAllFilled\" INTEGER," + // 11: isFieldAllFilled
                "\"dateDebutCollecte\" TEXT," + // 12: dateDebutCollecte
                "\"dateFinCollecte\" TEXT," + // 13: dateFinCollecte
                "\"dureeSaisie\" INTEGER," + // 14: dureeSaisie
                "\"isContreEnqueteMade\" INTEGER," + // 15: isContreEnqueteMade
                "\"codeAgentRecenceur\" TEXT," + // 16: codeAgentRecenceur
                "\"isVerified\" INTEGER);"); // 17: isVerified
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"tbl_deces\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Deces entity) {
        stmt.clearBindings();
 
        Long decesId = entity.getDecesId();
        if (decesId != null) {
            stmt.bindLong(1, decesId);
        }
 
        Long menageId = entity.getMenageId();
        if (menageId != null) {
            stmt.bindLong(2, menageId);
        }
 
        Long logeId = entity.getLogeId();
        if (logeId != null) {
            stmt.bindLong(3, logeId);
        }
 
        Long batimentId = entity.getBatimentId();
        if (batimentId != null) {
            stmt.bindLong(4, batimentId);
        }
 
        String sdeId = entity.getSdeId();
        if (sdeId != null) {
            stmt.bindString(5, sdeId);
        }
 
        Short qd2NoOrdre = entity.getQd2NoOrdre();
        if (qd2NoOrdre != null) {
            stmt.bindLong(6, qd2NoOrdre);
        }
 
        Short qd2aSexe = entity.getQd2aSexe();
        if (qd2aSexe != null) {
            stmt.bindLong(7, qd2aSexe);
        }
 
        String qd2bAgeDecede = entity.getQd2bAgeDecede();
        if (qd2bAgeDecede != null) {
            stmt.bindString(8, qd2bAgeDecede);
        }
 
        Short qd2c1CirconstanceDeces = entity.getQd2c1CirconstanceDeces();
        if (qd2c1CirconstanceDeces != null) {
            stmt.bindLong(9, qd2c1CirconstanceDeces);
        }
 
        Short qd2c2CauseDeces = entity.getQd2c2CauseDeces();
        if (qd2c2CauseDeces != null) {
            stmt.bindLong(10, qd2c2CauseDeces);
        }
 
        Short statut = entity.getStatut();
        if (statut != null) {
            stmt.bindLong(11, statut);
        }
 
        Boolean isFieldAllFilled = entity.getIsFieldAllFilled();
        if (isFieldAllFilled != null) {
            stmt.bindLong(12, isFieldAllFilled ? 1L: 0L);
        }
 
        String dateDebutCollecte = entity.getDateDebutCollecte();
        if (dateDebutCollecte != null) {
            stmt.bindString(13, dateDebutCollecte);
        }
 
        String dateFinCollecte = entity.getDateFinCollecte();
        if (dateFinCollecte != null) {
            stmt.bindString(14, dateFinCollecte);
        }
 
        Integer dureeSaisie = entity.getDureeSaisie();
        if (dureeSaisie != null) {
            stmt.bindLong(15, dureeSaisie);
        }
 
        Boolean isContreEnqueteMade = entity.getIsContreEnqueteMade();
        if (isContreEnqueteMade != null) {
            stmt.bindLong(16, isContreEnqueteMade ? 1L: 0L);
        }
 
        String codeAgentRecenceur = entity.getCodeAgentRecenceur();
        if (codeAgentRecenceur != null) {
            stmt.bindString(17, codeAgentRecenceur);
        }
 
        Boolean isVerified = entity.getIsVerified();
        if (isVerified != null) {
            stmt.bindLong(18, isVerified ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Deces readEntity(Cursor cursor, int offset) {
        Deces entity = new Deces( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // decesId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // menageId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // logeId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // batimentId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // sdeId
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5), // qd2NoOrdre
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6), // qd2aSexe
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // qd2bAgeDecede
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8), // qd2c1CirconstanceDeces
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9), // qd2c2CauseDeces
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10), // statut
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0, // isFieldAllFilled
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // dateDebutCollecte
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // dateFinCollecte
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // dureeSaisie
            cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0, // isContreEnqueteMade
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // codeAgentRecenceur
            cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0 // isVerified
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Deces entity, int offset) {
        entity.setDecesId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMenageId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLogeId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setBatimentId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setSdeId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setQd2NoOrdre(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5));
        entity.setQd2aSexe(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6));
        entity.setQd2bAgeDecede(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setQd2c1CirconstanceDeces(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8));
        entity.setQd2c2CauseDeces(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9));
        entity.setStatut(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10));
        entity.setIsFieldAllFilled(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
        entity.setDateDebutCollecte(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setDateFinCollecte(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setDureeSaisie(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setIsContreEnqueteMade(cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0);
        entity.setCodeAgentRecenceur(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setIsVerified(cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Deces entity, long rowId) {
        entity.setDecesId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Deces entity) {
        if(entity != null) {
            return entity.getDecesId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
