package ht.ihsi.rgph.mobile.backend.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ht.ihsi.rgph.mobile.backend.entities.Individu;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "tbl_individu".
*/
public class IndividuDao extends AbstractDao<Individu, Long> {

    public static final String TABLENAME = "tbl_individu";

    /**
     * Properties of entity Individu.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property IndividuId = new Property(0, Long.class, "individuId", true, "individuId");
        public final static Property MenageId = new Property(1, Long.class, "menageId", false, "menageId");
        public final static Property LogeId = new Property(2, Long.class, "logeId", false, "logeId");
        public final static Property BatimentId = new Property(3, Long.class, "batimentId", false, "batimentId");
        public final static Property SdeId = new Property(4, String.class, "sdeId", false, "sdeId");
        public final static Property Q1NoOrdre = new Property(5, Short.class, "q1NoOrdre", false, "q1NoOrdre");
        public final static Property Qp2APrenom = new Property(6, String.class, "qp2APrenom", false, "qp2APrenom");
        public final static Property Qp2BNom = new Property(7, String.class, "qp2BNom", false, "qp2BNom");
        public final static Property Qp3LienDeParente = new Property(8, Short.class, "qp3LienDeParente", false, "qp3LienDeParente");
        public final static Property Qp3HabiteDansMenage = new Property(9, Short.class, "qp3HabiteDansMenage", false, "qp3HabiteDansMenage");
        public final static Property Qp4Sexe = new Property(10, Short.class, "qp4Sexe", false, "qp4Sexe");
        public final static Property Qp5DateNaissanceJour = new Property(11, Short.class, "qp5DateNaissanceJour", false, "qp5DateNaissanceJour");
        public final static Property Qp5DateNaissanceMois = new Property(12, Short.class, "qp5DateNaissanceMois", false, "qp5DateNaissanceMois");
        public final static Property Qp5DateNaissanceAnnee = new Property(13, Integer.class, "Qp5DateNaissanceAnnee", false, "Qp5DateNaissanceAnnee");
        public final static Property Qp5bAge = new Property(14, Short.class, "qp5bAge", false, "qp5bAge");
        public final static Property Qp6religion = new Property(15, Short.class, "qp6religion", false, "qp6religion");
        public final static Property Qp6AutreReligion = new Property(16, String.class, "qp6AutreReligion", false, "qp6AutreReligion");
        public final static Property Qp7Nationalite = new Property(17, Short.class, "qp7Nationalite", false, "qp7Nationalite");
        public final static Property Qp7PaysNationalite = new Property(18, String.class, "qp7PaysNationalite", false, "qp7PaysNationalite");
        public final static Property Qp8MereEncoreVivante = new Property(19, Short.class, "qp8MereEncoreVivante", false, "qp8MereEncoreVivante");
        public final static Property Qp9EstPlusAge = new Property(20, Short.class, "qp9EstPlusAge", false, "qp9EstPlusAge");
        public final static Property Qp10LieuNaissance = new Property(21, Short.class, "qp10LieuNaissance", false, "qp10LieuNaissance");
        public final static Property Qp10CommuneNaissance = new Property(22, String.class, "qp10CommuneNaissance", false, "qp10CommuneNaissance");
        public final static Property Qp10VqseNaissance = new Property(23, String.class, "qp10VqseNaissance", false, "qp10VqseNaissance");
        public final static Property Qp10PaysNaissance = new Property(24, String.class, "qp10PaysNaissance", false, "qp10PaysNaissance");
        public final static Property Qp11PeriodeResidence = new Property(25, Short.class, "qp11PeriodeResidence", false, "qp11PeriodeResidence");
        public final static Property Qp12DomicileAvantRecensement = new Property(26, Short.class, "qp12DomicileAvantRecensement", false, "qp12DomicileAvantRecensement");
        public final static Property Qp12CommuneDomicileAvantRecensement = new Property(27, String.class, "qp12CommuneDomicileAvantRecensement", false, "qp12CommuneDomicileAvantRecensement");
        public final static Property Qp12VqseDomicileAvantRecensement = new Property(28, String.class, "qp12VqseDomicileAvantRecensement", false, "qp12VqseDomicileAvantRecensement");
        public final static Property Qp12PaysDomicileAvantRecensement = new Property(29, String.class, "qp12PaysDomicileAvantRecensement", false, "qp12PaysDomicileAvantRecensement");
        public final static Property Qe1EstAlphabetise = new Property(30, Short.class, "qe1EstAlphabetise", false, "qe1EstAlphabetise");
        public final static Property Qe2FreqentationScolaireOuUniv = new Property(31, Short.class, "qe2FreqentationScolaireOuUniv", false, "qe2FreqentationScolaireOuUniv");
        public final static Property Qe3typeEcoleOuUniv = new Property(32, Short.class, "qe3typeEcoleOuUniv", false, "qe3typeEcoleOuUniv");
        public final static Property Qe4aNiveauEtude = new Property(33, Short.class, "qe4aNiveauEtude", false, "qe4aNiveauEtude");
        public final static Property Qe4bDerniereClasseOUAneEtude = new Property(34, String.class, "qe4bDerniereClasseOUAneEtude", false, "qe4bDerniereClasseOUAneEtude");
        public final static Property Qe5DiplomeUniversitaire = new Property(35, Short.class, "qe5DiplomeUniversitaire", false, "qe5DiplomeUniversitaire");
        public final static Property Qe6DomaineEtudeUniversitaire = new Property(36, String.class, "qe6DomaineEtudeUniversitaire", false, "qe6DomaineEtudeUniversitaire");
        public final static Property Qaf1HandicapVoir = new Property(37, Short.class, "qaf1HandicapVoir", false, "qaf1HandicapVoir");
        public final static Property Qaf2HandicapEntendre = new Property(38, Short.class, "qaf2HandicapEntendre", false, "qaf2HandicapEntendre");
        public final static Property Qaf3HandicapMarcher = new Property(39, Short.class, "qaf3HandicapMarcher", false, "qaf3HandicapMarcher");
        public final static Property Qaf4HandicapSouvenir = new Property(40, Short.class, "qaf4HandicapSouvenir", false, "qaf4HandicapSouvenir");
        public final static Property Qaf5HandicapPourSeSoigner = new Property(41, Short.class, "qaf5HandicapPourSeSoigner", false, "qaf5HandicapPourSeSoigner");
        public final static Property Qaf6HandicapCommuniquer = new Property(42, Short.class, "qaf6HandicapCommuniquer", false, "qaf6HandicapCommuniquer");
        public final static Property Qt1PossessionTelCellulaire = new Property(43, Short.class, "qt1PossessionTelCellulaire", false, "qt1PossessionTelCellulaire");
        public final static Property Qt2UtilisationInternet = new Property(44, Short.class, "qt2UtilisationInternet", false, "qt2UtilisationInternet");
        public final static Property Qem1DejaVivreAutrePays = new Property(45, Short.class, "qem1DejaVivreAutrePays", false, "qem1DejaVivreAutrePays");
        public final static Property Qem1AutrePays = new Property(46, String.class, "qem1AutrePays", false, "qem1AutrePays");
        public final static Property Qem2MoisRetour = new Property(47, Short.class, "qem2MoisRetour", false, "qem2MoisRetour");
        public final static Property Qem2AnneeRetour = new Property(48, Integer.class, "qem2AnneeRetour", false, "qem2AnneeRetour");
        public final static Property Qsm1StatutMatrimonial = new Property(49, Short.class, "qsm1StatutMatrimonial", false, "qsm1StatutMatrimonial");
        public final static Property Qa1ActEconomiqueDerniereSemaine = new Property(50, Short.class, "qa1ActEconomiqueDerniereSemaine", false, "qa1ActEconomiqueDerniereSemaine");
        public final static Property Qa2ActAvoirDemele1 = new Property(51, Short.class, "qa2ActAvoirDemele1", false, "qa2ActAvoirDemele1");
        public final static Property Qa2ActDomestique2 = new Property(52, Short.class, "qa2ActDomestique2", false, "qa2ActDomestique2");
        public final static Property Qa2ActCultivateur3 = new Property(53, Short.class, "qa2ActCultivateur3", false, "qa2ActCultivateur3");
        public final static Property Qa2ActAiderParent4 = new Property(54, Short.class, "qa2ActAiderParent4", false, "qa2ActAiderParent4");
        public final static Property Qa2ActAutre5 = new Property(55, Short.class, "qa2ActAutre5", false, "qa2ActAutre5");
        public final static Property Qa3StatutEmploie = new Property(56, Short.class, "qa3StatutEmploie", false, "qa3StatutEmploie");
        public final static Property Qa4SecteurInstitutionnel = new Property(57, Short.class, "qa4SecteurInstitutionnel", false, "qa4SecteurInstitutionnel");
        public final static Property Qa5TypeBienProduitParEntreprise = new Property(58, String.class, "qa5TypeBienProduitParEntreprise", false, "qa5TypeBienProduitParEntreprise");
        public final static Property Qa5PreciserTypeBienProduitParEntreprise = new Property(59, String.class, "qa5PreciserTypeBienProduitParEntreprise", false, "qa5PreciserTypeBienProduitParEntreprise");
        public final static Property Qa6LieuActDerniereSemaine = new Property(60, Short.class, "qa6LieuActDerniereSemaine", false, "qa6LieuActDerniereSemaine");
        public final static Property Qa7FoncTravail = new Property(61, Short.class, "qa7FoncTravail", false, "qa7FoncTravail");
        public final static Property Qa8EntreprendreDemarcheTravail = new Property(62, Short.class, "qa8EntreprendreDemarcheTravail", false, "qa8EntreprendreDemarcheTravail");
        public final static Property Qa9VouloirTravailler = new Property(63, Short.class, "qa9VouloirTravailler", false, "qa9VouloirTravailler");
        public final static Property Qa10DisponibilitePourTravail = new Property(64, Short.class, "qa10DisponibilitePourTravail", false, "qa10DisponibilitePourTravail");
        public final static Property Qa11RecevoirTransfertArgent = new Property(65, Short.class, "qa11RecevoirTransfertArgent", false, "qa11RecevoirTransfertArgent");
        public final static Property Qf1aNbreEnfantNeVivantM = new Property(66, Integer.class, "qf1aNbreEnfantNeVivantM", false, "qf1aNbreEnfantNeVivantM");
        public final static Property Qf1bNbreEnfantNeVivantF = new Property(67, Integer.class, "qf1bNbreEnfantNeVivantF", false, "qf1bNbreEnfantNeVivantF");
        public final static Property Qf2aNbreEnfantVivantM = new Property(68, Integer.class, "qf2aNbreEnfantVivantM", false, "qf2aNbreEnfantVivantM");
        public final static Property Qf2bNbreEnfantVivantF = new Property(69, Integer.class, "qf2bNbreEnfantVivantF", false, "qf2bNbreEnfantVivantF");
        public final static Property Qf3DernierEnfantJour = new Property(70, Short.class, "qf3DernierEnfantJour", false, "qf3DernierEnfantJour");
        public final static Property Qf3DernierEnfantMois = new Property(71, Short.class, "qf3DernierEnfantMois", false, "qf3DernierEnfantMois");
        public final static Property Qf3DernierEnfantAnnee = new Property(72, Integer.class, "qf3DernierEnfantAnnee", false, "qf3DernierEnfantAnnee");
        public final static Property Qf4DENeVivantVit = new Property(73, Short.class, "qf4DENeVivantVit", false, "qf4DENeVivantVit");
        public final static Property Statut = new Property(74, Short.class, "statut", false, "statut");
        public final static Property IsFieldAllFilled = new Property(75, Boolean.class, "isFieldAllFilled", false, "isFieldAllFilled");
        public final static Property DateDebutCollecte = new Property(76, String.class, "dateDebutCollecte", false, "dateDebutCollecte");
        public final static Property DateFinCollecte = new Property(77, String.class, "dateFinCollecte", false, "dateFinCollecte");
        public final static Property DureeSaisie = new Property(78, Integer.class, "dureeSaisie", false, "dureeSaisie");
        public final static Property IsContreEnqueteMade = new Property(79, Boolean.class, "isContreEnqueteMade", false, "isContreEnqueteMade");
        public final static Property CodeAgentRecenceur = new Property(80, String.class, "codeAgentRecenceur", false, "codeAgentRecenceur");
        public final static Property IsVerified = new Property(81, Boolean.class, "isVerified", false, "isVerified");
    };


    public IndividuDao(DaoConfig config) {
        super(config);
    }
    
    public IndividuDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"tbl_individu\" (" + //
                "\"individuId\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: individuId
                "\"menageId\" INTEGER," + // 1: menageId
                "\"logeId\" INTEGER," + // 2: logeId
                "\"batimentId\" INTEGER," + // 3: batimentId
                "\"sdeId\" TEXT," + // 4: sdeId
                "\"q1NoOrdre\" INTEGER," + // 5: q1NoOrdre
                "\"qp2APrenom\" TEXT," + // 6: qp2APrenom
                "\"qp2BNom\" TEXT," + // 7: qp2BNom
                "\"qp3LienDeParente\" INTEGER," + // 8: qp3LienDeParente
                "\"qp3HabiteDansMenage\" INTEGER," + // 9: qp3HabiteDansMenage
                "\"qp4Sexe\" INTEGER," + // 10: qp4Sexe
                "\"qp5DateNaissanceJour\" INTEGER," + // 11: qp5DateNaissanceJour
                "\"qp5DateNaissanceMois\" INTEGER," + // 12: qp5DateNaissanceMois
                "\"Qp5DateNaissanceAnnee\" INTEGER," + // 13: Qp5DateNaissanceAnnee
                "\"qp5bAge\" INTEGER," + // 14: qp5bAge
                "\"qp6religion\" INTEGER," + // 15: qp6religion
                "\"qp6AutreReligion\" TEXT," + // 16: qp6AutreReligion
                "\"qp7Nationalite\" INTEGER," + // 17: qp7Nationalite
                "\"qp7PaysNationalite\" TEXT," + // 18: qp7PaysNationalite
                "\"qp8MereEncoreVivante\" INTEGER," + // 19: qp8MereEncoreVivante
                "\"qp9EstPlusAge\" INTEGER," + // 20: qp9EstPlusAge
                "\"qp10LieuNaissance\" INTEGER," + // 21: qp10LieuNaissance
                "\"qp10CommuneNaissance\" TEXT," + // 22: qp10CommuneNaissance
                "\"qp10VqseNaissance\" TEXT," + // 23: qp10VqseNaissance
                "\"qp10PaysNaissance\" TEXT," + // 24: qp10PaysNaissance
                "\"qp11PeriodeResidence\" INTEGER," + // 25: qp11PeriodeResidence
                "\"qp12DomicileAvantRecensement\" INTEGER," + // 26: qp12DomicileAvantRecensement
                "\"qp12CommuneDomicileAvantRecensement\" TEXT," + // 27: qp12CommuneDomicileAvantRecensement
                "\"qp12VqseDomicileAvantRecensement\" TEXT," + // 28: qp12VqseDomicileAvantRecensement
                "\"qp12PaysDomicileAvantRecensement\" TEXT," + // 29: qp12PaysDomicileAvantRecensement
                "\"qe1EstAlphabetise\" INTEGER," + // 30: qe1EstAlphabetise
                "\"qe2FreqentationScolaireOuUniv\" INTEGER," + // 31: qe2FreqentationScolaireOuUniv
                "\"qe3typeEcoleOuUniv\" INTEGER," + // 32: qe3typeEcoleOuUniv
                "\"qe4aNiveauEtude\" INTEGER," + // 33: qe4aNiveauEtude
                "\"qe4bDerniereClasseOUAneEtude\" TEXT," + // 34: qe4bDerniereClasseOUAneEtude
                "\"qe5DiplomeUniversitaire\" INTEGER," + // 35: qe5DiplomeUniversitaire
                "\"qe6DomaineEtudeUniversitaire\" TEXT," + // 36: qe6DomaineEtudeUniversitaire
                "\"qaf1HandicapVoir\" INTEGER," + // 37: qaf1HandicapVoir
                "\"qaf2HandicapEntendre\" INTEGER," + // 38: qaf2HandicapEntendre
                "\"qaf3HandicapMarcher\" INTEGER," + // 39: qaf3HandicapMarcher
                "\"qaf4HandicapSouvenir\" INTEGER," + // 40: qaf4HandicapSouvenir
                "\"qaf5HandicapPourSeSoigner\" INTEGER," + // 41: qaf5HandicapPourSeSoigner
                "\"qaf6HandicapCommuniquer\" INTEGER," + // 42: qaf6HandicapCommuniquer
                "\"qt1PossessionTelCellulaire\" INTEGER," + // 43: qt1PossessionTelCellulaire
                "\"qt2UtilisationInternet\" INTEGER," + // 44: qt2UtilisationInternet
                "\"qem1DejaVivreAutrePays\" INTEGER," + // 45: qem1DejaVivreAutrePays
                "\"qem1AutrePays\" TEXT," + // 46: qem1AutrePays
                "\"qem2MoisRetour\" INTEGER," + // 47: qem2MoisRetour
                "\"qem2AnneeRetour\" INTEGER," + // 48: qem2AnneeRetour
                "\"qsm1StatutMatrimonial\" INTEGER," + // 49: qsm1StatutMatrimonial
                "\"qa1ActEconomiqueDerniereSemaine\" INTEGER," + // 50: qa1ActEconomiqueDerniereSemaine
                "\"qa2ActAvoirDemele1\" INTEGER," + // 51: qa2ActAvoirDemele1
                "\"qa2ActDomestique2\" INTEGER," + // 52: qa2ActDomestique2
                "\"qa2ActCultivateur3\" INTEGER," + // 53: qa2ActCultivateur3
                "\"qa2ActAiderParent4\" INTEGER," + // 54: qa2ActAiderParent4
                "\"qa2ActAutre5\" INTEGER," + // 55: qa2ActAutre5
                "\"qa3StatutEmploie\" INTEGER," + // 56: qa3StatutEmploie
                "\"qa4SecteurInstitutionnel\" INTEGER," + // 57: qa4SecteurInstitutionnel
                "\"qa5TypeBienProduitParEntreprise\" TEXT," + // 58: qa5TypeBienProduitParEntreprise
                "\"qa5PreciserTypeBienProduitParEntreprise\" TEXT," + // 59: qa5PreciserTypeBienProduitParEntreprise
                "\"qa6LieuActDerniereSemaine\" INTEGER," + // 60: qa6LieuActDerniereSemaine
                "\"qa7FoncTravail\" INTEGER," + // 61: qa7FoncTravail
                "\"qa8EntreprendreDemarcheTravail\" INTEGER," + // 62: qa8EntreprendreDemarcheTravail
                "\"qa9VouloirTravailler\" INTEGER," + // 63: qa9VouloirTravailler
                "\"qa10DisponibilitePourTravail\" INTEGER," + // 64: qa10DisponibilitePourTravail
                "\"qa11RecevoirTransfertArgent\" INTEGER," + // 65: qa11RecevoirTransfertArgent
                "\"qf1aNbreEnfantNeVivantM\" INTEGER," + // 66: qf1aNbreEnfantNeVivantM
                "\"qf1bNbreEnfantNeVivantF\" INTEGER," + // 67: qf1bNbreEnfantNeVivantF
                "\"qf2aNbreEnfantVivantM\" INTEGER," + // 68: qf2aNbreEnfantVivantM
                "\"qf2bNbreEnfantVivantF\" INTEGER," + // 69: qf2bNbreEnfantVivantF
                "\"qf3DernierEnfantJour\" INTEGER," + // 70: qf3DernierEnfantJour
                "\"qf3DernierEnfantMois\" INTEGER," + // 71: qf3DernierEnfantMois
                "\"qf3DernierEnfantAnnee\" INTEGER," + // 72: qf3DernierEnfantAnnee
                "\"qf4DENeVivantVit\" INTEGER," + // 73: qf4DENeVivantVit
                "\"statut\" INTEGER," + // 74: statut
                "\"isFieldAllFilled\" INTEGER," + // 75: isFieldAllFilled
                "\"dateDebutCollecte\" TEXT," + // 76: dateDebutCollecte
                "\"dateFinCollecte\" TEXT," + // 77: dateFinCollecte
                "\"dureeSaisie\" INTEGER," + // 78: dureeSaisie
                "\"isContreEnqueteMade\" INTEGER," + // 79: isContreEnqueteMade
                "\"codeAgentRecenceur\" TEXT," + // 80: codeAgentRecenceur
                "\"isVerified\" INTEGER);"); // 81: isVerified
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"tbl_individu\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Individu entity) {
        stmt.clearBindings();
 
        Long individuId = entity.getIndividuId();
        if (individuId != null) {
            stmt.bindLong(1, individuId);
        }
 
        Long menageId = entity.getMenageId();
        if (menageId != null) {
            stmt.bindLong(2, menageId);
        }
 
        Long logeId = entity.getLogeId();
        if (logeId != null) {
            stmt.bindLong(3, logeId);
        }
 
        Long batimentId = entity.getBatimentId();
        if (batimentId != null) {
            stmt.bindLong(4, batimentId);
        }
 
        String sdeId = entity.getSdeId();
        if (sdeId != null) {
            stmt.bindString(5, sdeId);
        }
 
        Short q1NoOrdre = entity.getQ1NoOrdre();
        if (q1NoOrdre != null) {
            stmt.bindLong(6, q1NoOrdre);
        }
 
        String qp2APrenom = entity.getQp2APrenom();
        if (qp2APrenom != null) {
            stmt.bindString(7, qp2APrenom);
        }
 
        String qp2BNom = entity.getQp2BNom();
        if (qp2BNom != null) {
            stmt.bindString(8, qp2BNom);
        }
 
        Short qp3LienDeParente = entity.getQp3LienDeParente();
        if (qp3LienDeParente != null) {
            stmt.bindLong(9, qp3LienDeParente);
        }
 
        Short qp3HabiteDansMenage = entity.getQp3HabiteDansMenage();
        if (qp3HabiteDansMenage != null) {
            stmt.bindLong(10, qp3HabiteDansMenage);
        }
 
        Short qp4Sexe = entity.getQp4Sexe();
        if (qp4Sexe != null) {
            stmt.bindLong(11, qp4Sexe);
        }
 
        Short qp5DateNaissanceJour = entity.getQp5DateNaissanceJour();
        if (qp5DateNaissanceJour != null) {
            stmt.bindLong(12, qp5DateNaissanceJour);
        }
 
        Short qp5DateNaissanceMois = entity.getQp5DateNaissanceMois();
        if (qp5DateNaissanceMois != null) {
            stmt.bindLong(13, qp5DateNaissanceMois);
        }
 
        Integer Qp5DateNaissanceAnnee = entity.getQp5DateNaissanceAnnee();
        if (Qp5DateNaissanceAnnee != null) {
            stmt.bindLong(14, Qp5DateNaissanceAnnee);
        }
 
        Short qp5bAge = entity.getQp5bAge();
        if (qp5bAge != null) {
            stmt.bindLong(15, qp5bAge);
        }
 
        Short qp6religion = entity.getQp6religion();
        if (qp6religion != null) {
            stmt.bindLong(16, qp6religion);
        }
 
        String qp6AutreReligion = entity.getQp6AutreReligion();
        if (qp6AutreReligion != null) {
            stmt.bindString(17, qp6AutreReligion);
        }
 
        Short qp7Nationalite = entity.getQp7Nationalite();
        if (qp7Nationalite != null) {
            stmt.bindLong(18, qp7Nationalite);
        }
 
        String qp7PaysNationalite = entity.getQp7PaysNationalite();
        if (qp7PaysNationalite != null) {
            stmt.bindString(19, qp7PaysNationalite);
        }
 
        Short qp8MereEncoreVivante = entity.getQp8MereEncoreVivante();
        if (qp8MereEncoreVivante != null) {
            stmt.bindLong(20, qp8MereEncoreVivante);
        }
 
        Short qp9EstPlusAge = entity.getQp9EstPlusAge();
        if (qp9EstPlusAge != null) {
            stmt.bindLong(21, qp9EstPlusAge);
        }
 
        Short qp10LieuNaissance = entity.getQp10LieuNaissance();
        if (qp10LieuNaissance != null) {
            stmt.bindLong(22, qp10LieuNaissance);
        }
 
        String qp10CommuneNaissance = entity.getQp10CommuneNaissance();
        if (qp10CommuneNaissance != null) {
            stmt.bindString(23, qp10CommuneNaissance);
        }
 
        String qp10VqseNaissance = entity.getQp10VqseNaissance();
        if (qp10VqseNaissance != null) {
            stmt.bindString(24, qp10VqseNaissance);
        }
 
        String qp10PaysNaissance = entity.getQp10PaysNaissance();
        if (qp10PaysNaissance != null) {
            stmt.bindString(25, qp10PaysNaissance);
        }
 
        Short qp11PeriodeResidence = entity.getQp11PeriodeResidence();
        if (qp11PeriodeResidence != null) {
            stmt.bindLong(26, qp11PeriodeResidence);
        }
 
        Short qp12DomicileAvantRecensement = entity.getQp12DomicileAvantRecensement();
        if (qp12DomicileAvantRecensement != null) {
            stmt.bindLong(27, qp12DomicileAvantRecensement);
        }
 
        String qp12CommuneDomicileAvantRecensement = entity.getQp12CommuneDomicileAvantRecensement();
        if (qp12CommuneDomicileAvantRecensement != null) {
            stmt.bindString(28, qp12CommuneDomicileAvantRecensement);
        }
 
        String qp12VqseDomicileAvantRecensement = entity.getQp12VqseDomicileAvantRecensement();
        if (qp12VqseDomicileAvantRecensement != null) {
            stmt.bindString(29, qp12VqseDomicileAvantRecensement);
        }
 
        String qp12PaysDomicileAvantRecensement = entity.getQp12PaysDomicileAvantRecensement();
        if (qp12PaysDomicileAvantRecensement != null) {
            stmt.bindString(30, qp12PaysDomicileAvantRecensement);
        }
 
        Short qe1EstAlphabetise = entity.getQe1EstAlphabetise();
        if (qe1EstAlphabetise != null) {
            stmt.bindLong(31, qe1EstAlphabetise);
        }
 
        Short qe2FreqentationScolaireOuUniv = entity.getQe2FreqentationScolaireOuUniv();
        if (qe2FreqentationScolaireOuUniv != null) {
            stmt.bindLong(32, qe2FreqentationScolaireOuUniv);
        }
 
        Short qe3typeEcoleOuUniv = entity.getQe3typeEcoleOuUniv();
        if (qe3typeEcoleOuUniv != null) {
            stmt.bindLong(33, qe3typeEcoleOuUniv);
        }
 
        Short qe4aNiveauEtude = entity.getQe4aNiveauEtude();
        if (qe4aNiveauEtude != null) {
            stmt.bindLong(34, qe4aNiveauEtude);
        }
 
        String qe4bDerniereClasseOUAneEtude = entity.getQe4bDerniereClasseOUAneEtude();
        if (qe4bDerniereClasseOUAneEtude != null) {
            stmt.bindString(35, qe4bDerniereClasseOUAneEtude);
        }
 
        Short qe5DiplomeUniversitaire = entity.getQe5DiplomeUniversitaire();
        if (qe5DiplomeUniversitaire != null) {
            stmt.bindLong(36, qe5DiplomeUniversitaire);
        }
 
        String qe6DomaineEtudeUniversitaire = entity.getQe6DomaineEtudeUniversitaire();
        if (qe6DomaineEtudeUniversitaire != null) {
            stmt.bindString(37, qe6DomaineEtudeUniversitaire);
        }
 
        Short qaf1HandicapVoir = entity.getQaf1HandicapVoir();
        if (qaf1HandicapVoir != null) {
            stmt.bindLong(38, qaf1HandicapVoir);
        }
 
        Short qaf2HandicapEntendre = entity.getQaf2HandicapEntendre();
        if (qaf2HandicapEntendre != null) {
            stmt.bindLong(39, qaf2HandicapEntendre);
        }
 
        Short qaf3HandicapMarcher = entity.getQaf3HandicapMarcher();
        if (qaf3HandicapMarcher != null) {
            stmt.bindLong(40, qaf3HandicapMarcher);
        }
 
        Short qaf4HandicapSouvenir = entity.getQaf4HandicapSouvenir();
        if (qaf4HandicapSouvenir != null) {
            stmt.bindLong(41, qaf4HandicapSouvenir);
        }
 
        Short qaf5HandicapPourSeSoigner = entity.getQaf5HandicapPourSeSoigner();
        if (qaf5HandicapPourSeSoigner != null) {
            stmt.bindLong(42, qaf5HandicapPourSeSoigner);
        }
 
        Short qaf6HandicapCommuniquer = entity.getQaf6HandicapCommuniquer();
        if (qaf6HandicapCommuniquer != null) {
            stmt.bindLong(43, qaf6HandicapCommuniquer);
        }
 
        Short qt1PossessionTelCellulaire = entity.getQt1PossessionTelCellulaire();
        if (qt1PossessionTelCellulaire != null) {
            stmt.bindLong(44, qt1PossessionTelCellulaire);
        }
 
        Short qt2UtilisationInternet = entity.getQt2UtilisationInternet();
        if (qt2UtilisationInternet != null) {
            stmt.bindLong(45, qt2UtilisationInternet);
        }
 
        Short qem1DejaVivreAutrePays = entity.getQem1DejaVivreAutrePays();
        if (qem1DejaVivreAutrePays != null) {
            stmt.bindLong(46, qem1DejaVivreAutrePays);
        }
 
        String qem1AutrePays = entity.getQem1AutrePays();
        if (qem1AutrePays != null) {
            stmt.bindString(47, qem1AutrePays);
        }
 
        Short qem2MoisRetour = entity.getQem2MoisRetour();
        if (qem2MoisRetour != null) {
            stmt.bindLong(48, qem2MoisRetour);
        }
 
        Integer qem2AnneeRetour = entity.getQem2AnneeRetour();
        if (qem2AnneeRetour != null) {
            stmt.bindLong(49, qem2AnneeRetour);
        }
 
        Short qsm1StatutMatrimonial = entity.getQsm1StatutMatrimonial();
        if (qsm1StatutMatrimonial != null) {
            stmt.bindLong(50, qsm1StatutMatrimonial);
        }
 
        Short qa1ActEconomiqueDerniereSemaine = entity.getQa1ActEconomiqueDerniereSemaine();
        if (qa1ActEconomiqueDerniereSemaine != null) {
            stmt.bindLong(51, qa1ActEconomiqueDerniereSemaine);
        }
 
        Short qa2ActAvoirDemele1 = entity.getQa2ActAvoirDemele1();
        if (qa2ActAvoirDemele1 != null) {
            stmt.bindLong(52, qa2ActAvoirDemele1);
        }
 
        Short qa2ActDomestique2 = entity.getQa2ActDomestique2();
        if (qa2ActDomestique2 != null) {
            stmt.bindLong(53, qa2ActDomestique2);
        }
 
        Short qa2ActCultivateur3 = entity.getQa2ActCultivateur3();
        if (qa2ActCultivateur3 != null) {
            stmt.bindLong(54, qa2ActCultivateur3);
        }
 
        Short qa2ActAiderParent4 = entity.getQa2ActAiderParent4();
        if (qa2ActAiderParent4 != null) {
            stmt.bindLong(55, qa2ActAiderParent4);
        }
 
        Short qa2ActAutre5 = entity.getQa2ActAutre5();
        if (qa2ActAutre5 != null) {
            stmt.bindLong(56, qa2ActAutre5);
        }
 
        Short qa3StatutEmploie = entity.getQa3StatutEmploie();
        if (qa3StatutEmploie != null) {
            stmt.bindLong(57, qa3StatutEmploie);
        }
 
        Short qa4SecteurInstitutionnel = entity.getQa4SecteurInstitutionnel();
        if (qa4SecteurInstitutionnel != null) {
            stmt.bindLong(58, qa4SecteurInstitutionnel);
        }
 
        String qa5TypeBienProduitParEntreprise = entity.getQa5TypeBienProduitParEntreprise();
        if (qa5TypeBienProduitParEntreprise != null) {
            stmt.bindString(59, qa5TypeBienProduitParEntreprise);
        }
 
        String qa5PreciserTypeBienProduitParEntreprise = entity.getQa5PreciserTypeBienProduitParEntreprise();
        if (qa5PreciserTypeBienProduitParEntreprise != null) {
            stmt.bindString(60, qa5PreciserTypeBienProduitParEntreprise);
        }
 
        Short qa6LieuActDerniereSemaine = entity.getQa6LieuActDerniereSemaine();
        if (qa6LieuActDerniereSemaine != null) {
            stmt.bindLong(61, qa6LieuActDerniereSemaine);
        }
 
        Short qa7FoncTravail = entity.getQa7FoncTravail();
        if (qa7FoncTravail != null) {
            stmt.bindLong(62, qa7FoncTravail);
        }
 
        Short qa8EntreprendreDemarcheTravail = entity.getQa8EntreprendreDemarcheTravail();
        if (qa8EntreprendreDemarcheTravail != null) {
            stmt.bindLong(63, qa8EntreprendreDemarcheTravail);
        }
 
        Short qa9VouloirTravailler = entity.getQa9VouloirTravailler();
        if (qa9VouloirTravailler != null) {
            stmt.bindLong(64, qa9VouloirTravailler);
        }
 
        Short qa10DisponibilitePourTravail = entity.getQa10DisponibilitePourTravail();
        if (qa10DisponibilitePourTravail != null) {
            stmt.bindLong(65, qa10DisponibilitePourTravail);
        }
 
        Short qa11RecevoirTransfertArgent = entity.getQa11RecevoirTransfertArgent();
        if (qa11RecevoirTransfertArgent != null) {
            stmt.bindLong(66, qa11RecevoirTransfertArgent);
        }
 
        Integer qf1aNbreEnfantNeVivantM = entity.getQf1aNbreEnfantNeVivantM();
        if (qf1aNbreEnfantNeVivantM != null) {
            stmt.bindLong(67, qf1aNbreEnfantNeVivantM);
        }
 
        Integer qf1bNbreEnfantNeVivantF = entity.getQf1bNbreEnfantNeVivantF();
        if (qf1bNbreEnfantNeVivantF != null) {
            stmt.bindLong(68, qf1bNbreEnfantNeVivantF);
        }
 
        Integer qf2aNbreEnfantVivantM = entity.getQf2aNbreEnfantVivantM();
        if (qf2aNbreEnfantVivantM != null) {
            stmt.bindLong(69, qf2aNbreEnfantVivantM);
        }
 
        Integer qf2bNbreEnfantVivantF = entity.getQf2bNbreEnfantVivantF();
        if (qf2bNbreEnfantVivantF != null) {
            stmt.bindLong(70, qf2bNbreEnfantVivantF);
        }
 
        Short qf3DernierEnfantJour = entity.getQf3DernierEnfantJour();
        if (qf3DernierEnfantJour != null) {
            stmt.bindLong(71, qf3DernierEnfantJour);
        }
 
        Short qf3DernierEnfantMois = entity.getQf3DernierEnfantMois();
        if (qf3DernierEnfantMois != null) {
            stmt.bindLong(72, qf3DernierEnfantMois);
        }
 
        Integer qf3DernierEnfantAnnee = entity.getQf3DernierEnfantAnnee();
        if (qf3DernierEnfantAnnee != null) {
            stmt.bindLong(73, qf3DernierEnfantAnnee);
        }
 
        Short qf4DENeVivantVit = entity.getQf4DENeVivantVit();
        if (qf4DENeVivantVit != null) {
            stmt.bindLong(74, qf4DENeVivantVit);
        }
 
        Short statut = entity.getStatut();
        if (statut != null) {
            stmt.bindLong(75, statut);
        }
 
        Boolean isFieldAllFilled = entity.getIsFieldAllFilled();
        if (isFieldAllFilled != null) {
            stmt.bindLong(76, isFieldAllFilled ? 1L: 0L);
        }
 
        String dateDebutCollecte = entity.getDateDebutCollecte();
        if (dateDebutCollecte != null) {
            stmt.bindString(77, dateDebutCollecte);
        }
 
        String dateFinCollecte = entity.getDateFinCollecte();
        if (dateFinCollecte != null) {
            stmt.bindString(78, dateFinCollecte);
        }
 
        Integer dureeSaisie = entity.getDureeSaisie();
        if (dureeSaisie != null) {
            stmt.bindLong(79, dureeSaisie);
        }
 
        Boolean isContreEnqueteMade = entity.getIsContreEnqueteMade();
        if (isContreEnqueteMade != null) {
            stmt.bindLong(80, isContreEnqueteMade ? 1L: 0L);
        }
 
        String codeAgentRecenceur = entity.getCodeAgentRecenceur();
        if (codeAgentRecenceur != null) {
            stmt.bindString(81, codeAgentRecenceur);
        }
 
        Boolean isVerified = entity.getIsVerified();
        if (isVerified != null) {
            stmt.bindLong(82, isVerified ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Individu readEntity(Cursor cursor, int offset) {
        Individu entity = new Individu( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // individuId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // menageId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // logeId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // batimentId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // sdeId
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5), // q1NoOrdre
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // qp2APrenom
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // qp2BNom
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8), // qp3LienDeParente
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9), // qp3HabiteDansMenage
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10), // qp4Sexe
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11), // qp5DateNaissanceJour
            cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12), // qp5DateNaissanceMois
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // Qp5DateNaissanceAnnee
            cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14), // qp5bAge
            cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15), // qp6religion
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // qp6AutreReligion
            cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17), // qp7Nationalite
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // qp7PaysNationalite
            cursor.isNull(offset + 19) ? null : cursor.getShort(offset + 19), // qp8MereEncoreVivante
            cursor.isNull(offset + 20) ? null : cursor.getShort(offset + 20), // qp9EstPlusAge
            cursor.isNull(offset + 21) ? null : cursor.getShort(offset + 21), // qp10LieuNaissance
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // qp10CommuneNaissance
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // qp10VqseNaissance
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // qp10PaysNaissance
            cursor.isNull(offset + 25) ? null : cursor.getShort(offset + 25), // qp11PeriodeResidence
            cursor.isNull(offset + 26) ? null : cursor.getShort(offset + 26), // qp12DomicileAvantRecensement
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // qp12CommuneDomicileAvantRecensement
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // qp12VqseDomicileAvantRecensement
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // qp12PaysDomicileAvantRecensement
            cursor.isNull(offset + 30) ? null : cursor.getShort(offset + 30), // qe1EstAlphabetise
            cursor.isNull(offset + 31) ? null : cursor.getShort(offset + 31), // qe2FreqentationScolaireOuUniv
            cursor.isNull(offset + 32) ? null : cursor.getShort(offset + 32), // qe3typeEcoleOuUniv
            cursor.isNull(offset + 33) ? null : cursor.getShort(offset + 33), // qe4aNiveauEtude
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // qe4bDerniereClasseOUAneEtude
            cursor.isNull(offset + 35) ? null : cursor.getShort(offset + 35), // qe5DiplomeUniversitaire
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // qe6DomaineEtudeUniversitaire
            cursor.isNull(offset + 37) ? null : cursor.getShort(offset + 37), // qaf1HandicapVoir
            cursor.isNull(offset + 38) ? null : cursor.getShort(offset + 38), // qaf2HandicapEntendre
            cursor.isNull(offset + 39) ? null : cursor.getShort(offset + 39), // qaf3HandicapMarcher
            cursor.isNull(offset + 40) ? null : cursor.getShort(offset + 40), // qaf4HandicapSouvenir
            cursor.isNull(offset + 41) ? null : cursor.getShort(offset + 41), // qaf5HandicapPourSeSoigner
            cursor.isNull(offset + 42) ? null : cursor.getShort(offset + 42), // qaf6HandicapCommuniquer
            cursor.isNull(offset + 43) ? null : cursor.getShort(offset + 43), // qt1PossessionTelCellulaire
            cursor.isNull(offset + 44) ? null : cursor.getShort(offset + 44), // qt2UtilisationInternet
            cursor.isNull(offset + 45) ? null : cursor.getShort(offset + 45), // qem1DejaVivreAutrePays
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // qem1AutrePays
            cursor.isNull(offset + 47) ? null : cursor.getShort(offset + 47), // qem2MoisRetour
            cursor.isNull(offset + 48) ? null : cursor.getInt(offset + 48), // qem2AnneeRetour
            cursor.isNull(offset + 49) ? null : cursor.getShort(offset + 49), // qsm1StatutMatrimonial
            cursor.isNull(offset + 50) ? null : cursor.getShort(offset + 50), // qa1ActEconomiqueDerniereSemaine
            cursor.isNull(offset + 51) ? null : cursor.getShort(offset + 51), // qa2ActAvoirDemele1
            cursor.isNull(offset + 52) ? null : cursor.getShort(offset + 52), // qa2ActDomestique2
            cursor.isNull(offset + 53) ? null : cursor.getShort(offset + 53), // qa2ActCultivateur3
            cursor.isNull(offset + 54) ? null : cursor.getShort(offset + 54), // qa2ActAiderParent4
            cursor.isNull(offset + 55) ? null : cursor.getShort(offset + 55), // qa2ActAutre5
            cursor.isNull(offset + 56) ? null : cursor.getShort(offset + 56), // qa3StatutEmploie
            cursor.isNull(offset + 57) ? null : cursor.getShort(offset + 57), // qa4SecteurInstitutionnel
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // qa5TypeBienProduitParEntreprise
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // qa5PreciserTypeBienProduitParEntreprise
            cursor.isNull(offset + 60) ? null : cursor.getShort(offset + 60), // qa6LieuActDerniereSemaine
            cursor.isNull(offset + 61) ? null : cursor.getShort(offset + 61), // qa7FoncTravail
            cursor.isNull(offset + 62) ? null : cursor.getShort(offset + 62), // qa8EntreprendreDemarcheTravail
            cursor.isNull(offset + 63) ? null : cursor.getShort(offset + 63), // qa9VouloirTravailler
            cursor.isNull(offset + 64) ? null : cursor.getShort(offset + 64), // qa10DisponibilitePourTravail
            cursor.isNull(offset + 65) ? null : cursor.getShort(offset + 65), // qa11RecevoirTransfertArgent
            cursor.isNull(offset + 66) ? null : cursor.getInt(offset + 66), // qf1aNbreEnfantNeVivantM
            cursor.isNull(offset + 67) ? null : cursor.getInt(offset + 67), // qf1bNbreEnfantNeVivantF
            cursor.isNull(offset + 68) ? null : cursor.getInt(offset + 68), // qf2aNbreEnfantVivantM
            cursor.isNull(offset + 69) ? null : cursor.getInt(offset + 69), // qf2bNbreEnfantVivantF
            cursor.isNull(offset + 70) ? null : cursor.getShort(offset + 70), // qf3DernierEnfantJour
            cursor.isNull(offset + 71) ? null : cursor.getShort(offset + 71), // qf3DernierEnfantMois
            cursor.isNull(offset + 72) ? null : cursor.getInt(offset + 72), // qf3DernierEnfantAnnee
            cursor.isNull(offset + 73) ? null : cursor.getShort(offset + 73), // qf4DENeVivantVit
            cursor.isNull(offset + 74) ? null : cursor.getShort(offset + 74), // statut
            cursor.isNull(offset + 75) ? null : cursor.getShort(offset + 75) != 0, // isFieldAllFilled
            cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76), // dateDebutCollecte
            cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77), // dateFinCollecte
            cursor.isNull(offset + 78) ? null : cursor.getInt(offset + 78), // dureeSaisie
            cursor.isNull(offset + 79) ? null : cursor.getShort(offset + 79) != 0, // isContreEnqueteMade
            cursor.isNull(offset + 80) ? null : cursor.getString(offset + 80), // codeAgentRecenceur
            cursor.isNull(offset + 81) ? null : cursor.getShort(offset + 81) != 0 // isVerified
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Individu entity, int offset) {
        entity.setIndividuId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMenageId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLogeId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setBatimentId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setSdeId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setQ1NoOrdre(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5));
        entity.setQp2APrenom(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setQp2BNom(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setQp3LienDeParente(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8));
        entity.setQp3HabiteDansMenage(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9));
        entity.setQp4Sexe(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10));
        entity.setQp5DateNaissanceJour(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11));
        entity.setQp5DateNaissanceMois(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12));
        entity.setQp5DateNaissanceAnnee(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setQp5bAge(cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14));
        entity.setQp6religion(cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15));
        entity.setQp6AutreReligion(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setQp7Nationalite(cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17));
        entity.setQp7PaysNationalite(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setQp8MereEncoreVivante(cursor.isNull(offset + 19) ? null : cursor.getShort(offset + 19));
        entity.setQp9EstPlusAge(cursor.isNull(offset + 20) ? null : cursor.getShort(offset + 20));
        entity.setQp10LieuNaissance(cursor.isNull(offset + 21) ? null : cursor.getShort(offset + 21));
        entity.setQp10CommuneNaissance(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setQp10VqseNaissance(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setQp10PaysNaissance(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setQp11PeriodeResidence(cursor.isNull(offset + 25) ? null : cursor.getShort(offset + 25));
        entity.setQp12DomicileAvantRecensement(cursor.isNull(offset + 26) ? null : cursor.getShort(offset + 26));
        entity.setQp12CommuneDomicileAvantRecensement(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setQp12VqseDomicileAvantRecensement(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setQp12PaysDomicileAvantRecensement(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setQe1EstAlphabetise(cursor.isNull(offset + 30) ? null : cursor.getShort(offset + 30));
        entity.setQe2FreqentationScolaireOuUniv(cursor.isNull(offset + 31) ? null : cursor.getShort(offset + 31));
        entity.setQe3typeEcoleOuUniv(cursor.isNull(offset + 32) ? null : cursor.getShort(offset + 32));
        entity.setQe4aNiveauEtude(cursor.isNull(offset + 33) ? null : cursor.getShort(offset + 33));
        entity.setQe4bDerniereClasseOUAneEtude(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setQe5DiplomeUniversitaire(cursor.isNull(offset + 35) ? null : cursor.getShort(offset + 35));
        entity.setQe6DomaineEtudeUniversitaire(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setQaf1HandicapVoir(cursor.isNull(offset + 37) ? null : cursor.getShort(offset + 37));
        entity.setQaf2HandicapEntendre(cursor.isNull(offset + 38) ? null : cursor.getShort(offset + 38));
        entity.setQaf3HandicapMarcher(cursor.isNull(offset + 39) ? null : cursor.getShort(offset + 39));
        entity.setQaf4HandicapSouvenir(cursor.isNull(offset + 40) ? null : cursor.getShort(offset + 40));
        entity.setQaf5HandicapPourSeSoigner(cursor.isNull(offset + 41) ? null : cursor.getShort(offset + 41));
        entity.setQaf6HandicapCommuniquer(cursor.isNull(offset + 42) ? null : cursor.getShort(offset + 42));
        entity.setQt1PossessionTelCellulaire(cursor.isNull(offset + 43) ? null : cursor.getShort(offset + 43));
        entity.setQt2UtilisationInternet(cursor.isNull(offset + 44) ? null : cursor.getShort(offset + 44));
        entity.setQem1DejaVivreAutrePays(cursor.isNull(offset + 45) ? null : cursor.getShort(offset + 45));
        entity.setQem1AutrePays(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setQem2MoisRetour(cursor.isNull(offset + 47) ? null : cursor.getShort(offset + 47));
        entity.setQem2AnneeRetour(cursor.isNull(offset + 48) ? null : cursor.getInt(offset + 48));
        entity.setQsm1StatutMatrimonial(cursor.isNull(offset + 49) ? null : cursor.getShort(offset + 49));
        entity.setQa1ActEconomiqueDerniereSemaine(cursor.isNull(offset + 50) ? null : cursor.getShort(offset + 50));
        entity.setQa2ActAvoirDemele1(cursor.isNull(offset + 51) ? null : cursor.getShort(offset + 51));
        entity.setQa2ActDomestique2(cursor.isNull(offset + 52) ? null : cursor.getShort(offset + 52));
        entity.setQa2ActCultivateur3(cursor.isNull(offset + 53) ? null : cursor.getShort(offset + 53));
        entity.setQa2ActAiderParent4(cursor.isNull(offset + 54) ? null : cursor.getShort(offset + 54));
        entity.setQa2ActAutre5(cursor.isNull(offset + 55) ? null : cursor.getShort(offset + 55));
        entity.setQa3StatutEmploie(cursor.isNull(offset + 56) ? null : cursor.getShort(offset + 56));
        entity.setQa4SecteurInstitutionnel(cursor.isNull(offset + 57) ? null : cursor.getShort(offset + 57));
        entity.setQa5TypeBienProduitParEntreprise(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setQa5PreciserTypeBienProduitParEntreprise(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setQa6LieuActDerniereSemaine(cursor.isNull(offset + 60) ? null : cursor.getShort(offset + 60));
        entity.setQa7FoncTravail(cursor.isNull(offset + 61) ? null : cursor.getShort(offset + 61));
        entity.setQa8EntreprendreDemarcheTravail(cursor.isNull(offset + 62) ? null : cursor.getShort(offset + 62));
        entity.setQa9VouloirTravailler(cursor.isNull(offset + 63) ? null : cursor.getShort(offset + 63));
        entity.setQa10DisponibilitePourTravail(cursor.isNull(offset + 64) ? null : cursor.getShort(offset + 64));
        entity.setQa11RecevoirTransfertArgent(cursor.isNull(offset + 65) ? null : cursor.getShort(offset + 65));
        entity.setQf1aNbreEnfantNeVivantM(cursor.isNull(offset + 66) ? null : cursor.getInt(offset + 66));
        entity.setQf1bNbreEnfantNeVivantF(cursor.isNull(offset + 67) ? null : cursor.getInt(offset + 67));
        entity.setQf2aNbreEnfantVivantM(cursor.isNull(offset + 68) ? null : cursor.getInt(offset + 68));
        entity.setQf2bNbreEnfantVivantF(cursor.isNull(offset + 69) ? null : cursor.getInt(offset + 69));
        entity.setQf3DernierEnfantJour(cursor.isNull(offset + 70) ? null : cursor.getShort(offset + 70));
        entity.setQf3DernierEnfantMois(cursor.isNull(offset + 71) ? null : cursor.getShort(offset + 71));
        entity.setQf3DernierEnfantAnnee(cursor.isNull(offset + 72) ? null : cursor.getInt(offset + 72));
        entity.setQf4DENeVivantVit(cursor.isNull(offset + 73) ? null : cursor.getShort(offset + 73));
        entity.setStatut(cursor.isNull(offset + 74) ? null : cursor.getShort(offset + 74));
        entity.setIsFieldAllFilled(cursor.isNull(offset + 75) ? null : cursor.getShort(offset + 75) != 0);
        entity.setDateDebutCollecte(cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76));
        entity.setDateFinCollecte(cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77));
        entity.setDureeSaisie(cursor.isNull(offset + 78) ? null : cursor.getInt(offset + 78));
        entity.setIsContreEnqueteMade(cursor.isNull(offset + 79) ? null : cursor.getShort(offset + 79) != 0);
        entity.setCodeAgentRecenceur(cursor.isNull(offset + 80) ? null : cursor.getString(offset + 80));
        entity.setIsVerified(cursor.isNull(offset + 81) ? null : cursor.getShort(offset + 81) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Individu entity, long rowId) {
        entity.setIndividuId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Individu entity) {
        if(entity != null) {
            return entity.getIndividuId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
