package ht.ihsi.rgph.mobile.backend.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ht.ihsi.rgph.mobile.backend.entities.Pays;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "tbl_pays".
*/
public class PaysDao extends AbstractDao<Pays, Void> {

    public static final String TABLENAME = "tbl_pays";

    /**
     * Properties of entity Pays.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property CodePays = new Property(0, String.class, "CodePays", false, "CodePays");
        public final static Property NomPays = new Property(1, String.class, "NomPays", false, "NomPays");
    };


    public PaysDao(DaoConfig config) {
        super(config);
    }
    
    public PaysDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"tbl_pays\" (" + //
                "\"CodePays\" TEXT NOT NULL UNIQUE ," + // 0: CodePays
                "\"NomPays\" TEXT);"); // 1: NomPays
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"tbl_pays\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Pays entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getCodePays());
 
        String NomPays = entity.getNomPays();
        if (NomPays != null) {
            stmt.bindString(2, NomPays);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Pays readEntity(Cursor cursor, int offset) {
        Pays entity = new Pays( //
            cursor.getString(offset + 0), // CodePays
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // NomPays
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Pays entity, int offset) {
        entity.setCodePays(cursor.getString(offset + 0));
        entity.setNomPays(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Pays entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Pays entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
