package ht.ihsi.rgph.mobile.epc.backend.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_AncienMembre".
 */
public class AncienMembre {

    private Long ancienMembreId;
    private Long menageId;
    private Long logeId;
    private Long batimentId;
    private String sdeId;
    private Short q1NoOrdre;
    private String qp2APrenom;
    private String qp2BNom;
    private Short qp4Sexe;
    private Short q5EstMortOuQuitter;
    private Short q6HabiteDansMenage;
    private Short q7DateQuitterMenageJour;
    private Short q7DateQuitterMenageMois;
    private Integer q7DateQuitterMenageAnnee;
    private Short q7bDateMouriJour;
    private Short q7bDateMouriMois;
    private Integer q7bDateMouriAnnee;
    private Short q8DateNaissanceJour;
    private Short q8DateNaissanceMois;
    private Integer q8DateNaissanceAnnee;
    private Integer q9Age;
    private Short q10LienDeParente;
    private Short q11Nationalite;
    private String q11PaysNationalite;
    private Short q12NiveauEtude;
    private Short q12StatutMatrimonial;
    private Short statut;
    private Boolean isValidated;
    private Boolean isFieldAllFilled;
    private String dateDebutCollecte;
    private String dateFinCollecte;
    private Integer dureeSaisie;
    private Boolean isContreEnqueteMade;
    private String codeAgentRecenceur;
    private Boolean isVerified;

    public AncienMembre() {
    }

    public AncienMembre(Long ancienMembreId) {
        this.ancienMembreId = ancienMembreId;
    }

    public AncienMembre(Long ancienMembreId, Long menageId, Long logeId, Long batimentId, String sdeId, Short q1NoOrdre, String qp2APrenom, String qp2BNom, Short qp4Sexe, Short q5EstMortOuQuitter, Short q6HabiteDansMenage, Short q7DateQuitterMenageJour, Short q7DateQuitterMenageMois, Integer q7DateQuitterMenageAnnee, Short q7bDateMouriJour, Short q7bDateMouriMois, Integer q7bDateMouriAnnee, Short q8DateNaissanceJour, Short q8DateNaissanceMois, Integer q8DateNaissanceAnnee, Integer q9Age, Short q10LienDeParente, Short q11Nationalite, String q11PaysNationalite, Short q12NiveauEtude, Short q12StatutMatrimonial, Short statut, Boolean isValidated, Boolean isFieldAllFilled, String dateDebutCollecte, String dateFinCollecte, Integer dureeSaisie, Boolean isContreEnqueteMade, String codeAgentRecenceur, Boolean isVerified) {
        this.ancienMembreId = ancienMembreId;
        this.menageId = menageId;
        this.logeId = logeId;
        this.batimentId = batimentId;
        this.sdeId = sdeId;
        this.q1NoOrdre = q1NoOrdre;
        this.qp2APrenom = qp2APrenom;
        this.qp2BNom = qp2BNom;
        this.qp4Sexe = qp4Sexe;
        this.q5EstMortOuQuitter = q5EstMortOuQuitter;
        this.q6HabiteDansMenage = q6HabiteDansMenage;
        this.q7DateQuitterMenageJour = q7DateQuitterMenageJour;
        this.q7DateQuitterMenageMois = q7DateQuitterMenageMois;
        this.q7DateQuitterMenageAnnee = q7DateQuitterMenageAnnee;
        this.q7bDateMouriJour = q7bDateMouriJour;
        this.q7bDateMouriMois = q7bDateMouriMois;
        this.q7bDateMouriAnnee = q7bDateMouriAnnee;
        this.q8DateNaissanceJour = q8DateNaissanceJour;
        this.q8DateNaissanceMois = q8DateNaissanceMois;
        this.q8DateNaissanceAnnee = q8DateNaissanceAnnee;
        this.q9Age = q9Age;
        this.q10LienDeParente = q10LienDeParente;
        this.q11Nationalite = q11Nationalite;
        this.q11PaysNationalite = q11PaysNationalite;
        this.q12NiveauEtude = q12NiveauEtude;
        this.q12StatutMatrimonial = q12StatutMatrimonial;
        this.statut = statut;
        this.isValidated = isValidated;
        this.isFieldAllFilled = isFieldAllFilled;
        this.dateDebutCollecte = dateDebutCollecte;
        this.dateFinCollecte = dateFinCollecte;
        this.dureeSaisie = dureeSaisie;
        this.isContreEnqueteMade = isContreEnqueteMade;
        this.codeAgentRecenceur = codeAgentRecenceur;
        this.isVerified = isVerified;
    }

    public Long getAncienMembreId() {
        return ancienMembreId;
    }

    public void setAncienMembreId(Long ancienMembreId) {
        this.ancienMembreId = ancienMembreId;
    }

    public Long getMenageId() {
        return menageId;
    }

    public void setMenageId(Long menageId) {
        this.menageId = menageId;
    }

    public Long getLogeId() {
        return logeId;
    }

    public void setLogeId(Long logeId) {
        this.logeId = logeId;
    }

    public Long getBatimentId() {
        return batimentId;
    }

    public void setBatimentId(Long batimentId) {
        this.batimentId = batimentId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public Short getQ1NoOrdre() {
        return q1NoOrdre;
    }

    public void setQ1NoOrdre(Short q1NoOrdre) {
        this.q1NoOrdre = q1NoOrdre;
    }

    public String getQp2APrenom() {
        return qp2APrenom;
    }

    public void setQp2APrenom(String qp2APrenom) {
        this.qp2APrenom = qp2APrenom;
    }

    public String getQp2BNom() {
        return qp2BNom;
    }

    public void setQp2BNom(String qp2BNom) {
        this.qp2BNom = qp2BNom;
    }

    public Short getQp4Sexe() {
        return qp4Sexe;
    }

    public void setQp4Sexe(Short qp4Sexe) {
        this.qp4Sexe = qp4Sexe;
    }

    public Short getQ5EstMortOuQuitter() {
        return q5EstMortOuQuitter;
    }

    public void setQ5EstMortOuQuitter(Short q5EstMortOuQuitter) {
        this.q5EstMortOuQuitter = q5EstMortOuQuitter;
    }

    public Short getQ6HabiteDansMenage() {
        return q6HabiteDansMenage;
    }

    public void setQ6HabiteDansMenage(Short q6HabiteDansMenage) {
        this.q6HabiteDansMenage = q6HabiteDansMenage;
    }

    public Short getQ7DateQuitterMenageJour() {
        return q7DateQuitterMenageJour;
    }

    public void setQ7DateQuitterMenageJour(Short q7DateQuitterMenageJour) {
        this.q7DateQuitterMenageJour = q7DateQuitterMenageJour;
    }

    public Short getQ7DateQuitterMenageMois() {
        return q7DateQuitterMenageMois;
    }

    public void setQ7DateQuitterMenageMois(Short q7DateQuitterMenageMois) {
        this.q7DateQuitterMenageMois = q7DateQuitterMenageMois;
    }

    public Integer getQ7DateQuitterMenageAnnee() {
        return q7DateQuitterMenageAnnee;
    }

    public void setQ7DateQuitterMenageAnnee(Integer q7DateQuitterMenageAnnee) {
        this.q7DateQuitterMenageAnnee = q7DateQuitterMenageAnnee;
    }

    public Short getQ7bDateMouriJour() {
        return q7bDateMouriJour;
    }

    public void setQ7bDateMouriJour(Short q7bDateMouriJour) {
        this.q7bDateMouriJour = q7bDateMouriJour;
    }

    public Short getQ7bDateMouriMois() {
        return q7bDateMouriMois;
    }

    public void setQ7bDateMouriMois(Short q7bDateMouriMois) {
        this.q7bDateMouriMois = q7bDateMouriMois;
    }

    public Integer getQ7bDateMouriAnnee() {
        return q7bDateMouriAnnee;
    }

    public void setQ7bDateMouriAnnee(Integer q7bDateMouriAnnee) {
        this.q7bDateMouriAnnee = q7bDateMouriAnnee;
    }

    public Short getQ8DateNaissanceJour() {
        return q8DateNaissanceJour;
    }

    public void setQ8DateNaissanceJour(Short q8DateNaissanceJour) {
        this.q8DateNaissanceJour = q8DateNaissanceJour;
    }

    public Short getQ8DateNaissanceMois() {
        return q8DateNaissanceMois;
    }

    public void setQ8DateNaissanceMois(Short q8DateNaissanceMois) {
        this.q8DateNaissanceMois = q8DateNaissanceMois;
    }

    public Integer getQ8DateNaissanceAnnee() {
        return q8DateNaissanceAnnee;
    }

    public void setQ8DateNaissanceAnnee(Integer q8DateNaissanceAnnee) {
        this.q8DateNaissanceAnnee = q8DateNaissanceAnnee;
    }

    public Integer getQ9Age() {
        return q9Age;
    }

    public void setQ9Age(Integer q9Age) {
        this.q9Age = q9Age;
    }

    public Short getQ10LienDeParente() {
        return q10LienDeParente;
    }

    public void setQ10LienDeParente(Short q10LienDeParente) {
        this.q10LienDeParente = q10LienDeParente;
    }

    public Short getQ11Nationalite() {
        return q11Nationalite;
    }

    public void setQ11Nationalite(Short q11Nationalite) {
        this.q11Nationalite = q11Nationalite;
    }

    public String getQ11PaysNationalite() {
        return q11PaysNationalite;
    }

    public void setQ11PaysNationalite(String q11PaysNationalite) {
        this.q11PaysNationalite = q11PaysNationalite;
    }

    public Short getQ12NiveauEtude() {
        return q12NiveauEtude;
    }

    public void setQ12NiveauEtude(Short q12NiveauEtude) {
        this.q12NiveauEtude = q12NiveauEtude;
    }

    public Short getQ12StatutMatrimonial() {
        return q12StatutMatrimonial;
    }

    public void setQ12StatutMatrimonial(Short q12StatutMatrimonial) {
        this.q12StatutMatrimonial = q12StatutMatrimonial;
    }

    public Short getStatut() {
        return statut;
    }

    public void setStatut(Short statut) {
        this.statut = statut;
    }

    public Boolean getIsValidated() {
        return isValidated;
    }

    public void setIsValidated(Boolean isValidated) {
        this.isValidated = isValidated;
    }

    public Boolean getIsFieldAllFilled() {
        return isFieldAllFilled;
    }

    public void setIsFieldAllFilled(Boolean isFieldAllFilled) {
        this.isFieldAllFilled = isFieldAllFilled;
    }

    public String getDateDebutCollecte() {
        return dateDebutCollecte;
    }

    public void setDateDebutCollecte(String dateDebutCollecte) {
        this.dateDebutCollecte = dateDebutCollecte;
    }

    public String getDateFinCollecte() {
        return dateFinCollecte;
    }

    public void setDateFinCollecte(String dateFinCollecte) {
        this.dateFinCollecte = dateFinCollecte;
    }

    public Integer getDureeSaisie() {
        return dureeSaisie;
    }

    public void setDureeSaisie(Integer dureeSaisie) {
        this.dureeSaisie = dureeSaisie;
    }

    public Boolean getIsContreEnqueteMade() {
        return isContreEnqueteMade;
    }

    public void setIsContreEnqueteMade(Boolean isContreEnqueteMade) {
        this.isContreEnqueteMade = isContreEnqueteMade;
    }

    public String getCodeAgentRecenceur() {
        return codeAgentRecenceur;
    }

    public void setCodeAgentRecenceur(String codeAgentRecenceur) {
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

}
