package ht.ihsi.rgph.mobile.epc.backend.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_categorie_question".
 */
public class CategorieQuestion {

    /** Not-null value. */
    private String codeCategorie;
    /** Not-null value. */
    private String categorieQuestion;
    private String detailsCategorie;
    private String sousDetailsCategorie;

    public CategorieQuestion() {
    }

    public CategorieQuestion(String codeCategorie, String categorieQuestion, String detailsCategorie, String sousDetailsCategorie) {
        this.codeCategorie = codeCategorie;
        this.categorieQuestion = categorieQuestion;
        this.detailsCategorie = detailsCategorie;
        this.sousDetailsCategorie = sousDetailsCategorie;
    }

    /** Not-null value. */
    public String getCodeCategorie() {
        return codeCategorie;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodeCategorie(String codeCategorie) {
        this.codeCategorie = codeCategorie;
    }

    /** Not-null value. */
    public String getCategorieQuestion() {
        return categorieQuestion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategorieQuestion(String categorieQuestion) {
        this.categorieQuestion = categorieQuestion;
    }

    public String getDetailsCategorie() {
        return detailsCategorie;
    }

    public void setDetailsCategorie(String detailsCategorie) {
        this.detailsCategorie = detailsCategorie;
    }

    public String getSousDetailsCategorie() {
        return sousDetailsCategorie;
    }

    public void setSousDetailsCategorie(String sousDetailsCategorie) {
        this.sousDetailsCategorie = sousDetailsCategorie;
    }

}
