package ht.ihsi.rgph.mobile.epc.backend.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_deces".
 */
public class Deces {

    private Long decesId;
    private Long menageId;
    private Long logeId;
    private Long batimentId;
    private String sdeId;
    private Short qd2NoOrdre;
    private Short qd2aSexe;
    private String qd2bAgeDecede;
    private Short qd2c1CirconstanceDeces;
    private Short qd2c2CauseDeces;
    private Short statut;
    private Boolean isFieldAllFilled;
    private String dateDebutCollecte;
    private String dateFinCollecte;
    private Integer dureeSaisie;
    private Boolean isContreEnqueteMade;
    private String codeAgentRecenceur;
    private Boolean isVerified;

    public Deces() {
    }

    public Deces(Long decesId) {
        this.decesId = decesId;
    }

    public Deces(Long decesId, Long menageId, Long logeId, Long batimentId, String sdeId, Short qd2NoOrdre, Short qd2aSexe, String qd2bAgeDecede, Short qd2c1CirconstanceDeces, Short qd2c2CauseDeces, Short statut, Boolean isFieldAllFilled, String dateDebutCollecte, String dateFinCollecte, Integer dureeSaisie, Boolean isContreEnqueteMade, String codeAgentRecenceur, Boolean isVerified) {
        this.decesId = decesId;
        this.menageId = menageId;
        this.logeId = logeId;
        this.batimentId = batimentId;
        this.sdeId = sdeId;
        this.qd2NoOrdre = qd2NoOrdre;
        this.qd2aSexe = qd2aSexe;
        this.qd2bAgeDecede = qd2bAgeDecede;
        this.qd2c1CirconstanceDeces = qd2c1CirconstanceDeces;
        this.qd2c2CauseDeces = qd2c2CauseDeces;
        this.statut = statut;
        this.isFieldAllFilled = isFieldAllFilled;
        this.dateDebutCollecte = dateDebutCollecte;
        this.dateFinCollecte = dateFinCollecte;
        this.dureeSaisie = dureeSaisie;
        this.isContreEnqueteMade = isContreEnqueteMade;
        this.codeAgentRecenceur = codeAgentRecenceur;
        this.isVerified = isVerified;
    }

    public Long getDecesId() {
        return decesId;
    }

    public void setDecesId(Long decesId) {
        this.decesId = decesId;
    }

    public Long getMenageId() {
        return menageId;
    }

    public void setMenageId(Long menageId) {
        this.menageId = menageId;
    }

    public Long getLogeId() {
        return logeId;
    }

    public void setLogeId(Long logeId) {
        this.logeId = logeId;
    }

    public Long getBatimentId() {
        return batimentId;
    }

    public void setBatimentId(Long batimentId) {
        this.batimentId = batimentId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public Short getQd2NoOrdre() {
        return qd2NoOrdre;
    }

    public void setQd2NoOrdre(Short qd2NoOrdre) {
        this.qd2NoOrdre = qd2NoOrdre;
    }

    public Short getQd2aSexe() {
        return qd2aSexe;
    }

    public void setQd2aSexe(Short qd2aSexe) {
        this.qd2aSexe = qd2aSexe;
    }

    public String getQd2bAgeDecede() {
        return qd2bAgeDecede;
    }

    public void setQd2bAgeDecede(String qd2bAgeDecede) {
        this.qd2bAgeDecede = qd2bAgeDecede;
    }

    public Short getQd2c1CirconstanceDeces() {
        return qd2c1CirconstanceDeces;
    }

    public void setQd2c1CirconstanceDeces(Short qd2c1CirconstanceDeces) {
        this.qd2c1CirconstanceDeces = qd2c1CirconstanceDeces;
    }

    public Short getQd2c2CauseDeces() {
        return qd2c2CauseDeces;
    }

    public void setQd2c2CauseDeces(Short qd2c2CauseDeces) {
        this.qd2c2CauseDeces = qd2c2CauseDeces;
    }

    public Short getStatut() {
        return statut;
    }

    public void setStatut(Short statut) {
        this.statut = statut;
    }

    public Boolean getIsFieldAllFilled() {
        return isFieldAllFilled;
    }

    public void setIsFieldAllFilled(Boolean isFieldAllFilled) {
        this.isFieldAllFilled = isFieldAllFilled;
    }

    public String getDateDebutCollecte() {
        return dateDebutCollecte;
    }

    public void setDateDebutCollecte(String dateDebutCollecte) {
        this.dateDebutCollecte = dateDebutCollecte;
    }

    public String getDateFinCollecte() {
        return dateFinCollecte;
    }

    public void setDateFinCollecte(String dateFinCollecte) {
        this.dateFinCollecte = dateFinCollecte;
    }

    public Integer getDureeSaisie() {
        return dureeSaisie;
    }

    public void setDureeSaisie(Integer dureeSaisie) {
        this.dureeSaisie = dureeSaisie;
    }

    public Boolean getIsContreEnqueteMade() {
        return isContreEnqueteMade;
    }

    public void setIsContreEnqueteMade(Boolean isContreEnqueteMade) {
        this.isContreEnqueteMade = isContreEnqueteMade;
    }

    public String getCodeAgentRecenceur() {
        return codeAgentRecenceur;
    }

    public void setCodeAgentRecenceur(String codeAgentRecenceur) {
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

}
