package ht.ihsi.rgph.mobile.epc.backend.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_domaine_etude".
 */
public class DomaineEtude {

    /** Not-null value. */
    private String Code;
    private String NomDomaine;

    public DomaineEtude() {
    }

    public DomaineEtude(String Code, String NomDomaine) {
        this.Code = Code;
        this.NomDomaine = NomDomaine;
    }

    /** Not-null value. */
    public String getCode() {
        return Code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCode(String Code) {
        this.Code = Code;
    }

    public String getNomDomaine() {
        return NomDomaine;
    }

    public void setNomDomaine(String NomDomaine) {
        this.NomDomaine = NomDomaine;
    }

}
