package ht.ihsi.rgph.mobile.epc.backend.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_emigre".
 */
public class Emigre {

    private Long emigreId;
    private Long menageId;
    private Long logeId;
    private Long batimentId;
    private String sdeId;
    private Short qn1numeroOrdre;
    private String qn2aNomComplet;
    private Short qn2bSexe;
    private String qn2cAgeAuMomentDepart;
    private Short qn2dVivantToujours;
    private Short qn2eDernierPaysResidence;
    private Short statut;
    private Boolean isFieldAllFilled;
    private String dateDebutCollecte;
    private String dateFinCollecte;
    private Integer dureeSaisie;
    private String codeAgentRecenceur;
    private Boolean isVerified;

    public Emigre() {
    }

    public Emigre(Long emigreId) {
        this.emigreId = emigreId;
    }

    public Emigre(Long emigreId, Long menageId, Long logeId, Long batimentId, String sdeId, Short qn1numeroOrdre, String qn2aNomComplet, Short qn2bSexe, String qn2cAgeAuMomentDepart, Short qn2dVivantToujours, Short qn2eDernierPaysResidence, Short statut, Boolean isFieldAllFilled, String dateDebutCollecte, String dateFinCollecte, Integer dureeSaisie, String codeAgentRecenceur, Boolean isVerified) {
        this.emigreId = emigreId;
        this.menageId = menageId;
        this.logeId = logeId;
        this.batimentId = batimentId;
        this.sdeId = sdeId;
        this.qn1numeroOrdre = qn1numeroOrdre;
        this.qn2aNomComplet = qn2aNomComplet;
        this.qn2bSexe = qn2bSexe;
        this.qn2cAgeAuMomentDepart = qn2cAgeAuMomentDepart;
        this.qn2dVivantToujours = qn2dVivantToujours;
        this.qn2eDernierPaysResidence = qn2eDernierPaysResidence;
        this.statut = statut;
        this.isFieldAllFilled = isFieldAllFilled;
        this.dateDebutCollecte = dateDebutCollecte;
        this.dateFinCollecte = dateFinCollecte;
        this.dureeSaisie = dureeSaisie;
        this.codeAgentRecenceur = codeAgentRecenceur;
        this.isVerified = isVerified;
    }

    public Long getEmigreId() {
        return emigreId;
    }

    public void setEmigreId(Long emigreId) {
        this.emigreId = emigreId;
    }

    public Long getMenageId() {
        return menageId;
    }

    public void setMenageId(Long menageId) {
        this.menageId = menageId;
    }

    public Long getLogeId() {
        return logeId;
    }

    public void setLogeId(Long logeId) {
        this.logeId = logeId;
    }

    public Long getBatimentId() {
        return batimentId;
    }

    public void setBatimentId(Long batimentId) {
        this.batimentId = batimentId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public Short getQn1numeroOrdre() {
        return qn1numeroOrdre;
    }

    public void setQn1numeroOrdre(Short qn1numeroOrdre) {
        this.qn1numeroOrdre = qn1numeroOrdre;
    }

    public String getQn2aNomComplet() {
        return qn2aNomComplet;
    }

    public void setQn2aNomComplet(String qn2aNomComplet) {
        this.qn2aNomComplet = qn2aNomComplet;
    }

    public Short getQn2bSexe() {
        return qn2bSexe;
    }

    public void setQn2bSexe(Short qn2bSexe) {
        this.qn2bSexe = qn2bSexe;
    }

    public String getQn2cAgeAuMomentDepart() {
        return qn2cAgeAuMomentDepart;
    }

    public void setQn2cAgeAuMomentDepart(String qn2cAgeAuMomentDepart) {
        this.qn2cAgeAuMomentDepart = qn2cAgeAuMomentDepart;
    }

    public Short getQn2dVivantToujours() {
        return qn2dVivantToujours;
    }

    public void setQn2dVivantToujours(Short qn2dVivantToujours) {
        this.qn2dVivantToujours = qn2dVivantToujours;
    }

    public Short getQn2eDernierPaysResidence() {
        return qn2eDernierPaysResidence;
    }

    public void setQn2eDernierPaysResidence(Short qn2eDernierPaysResidence) {
        this.qn2eDernierPaysResidence = qn2eDernierPaysResidence;
    }

    public Short getStatut() {
        return statut;
    }

    public void setStatut(Short statut) {
        this.statut = statut;
    }

    public Boolean getIsFieldAllFilled() {
        return isFieldAllFilled;
    }

    public void setIsFieldAllFilled(Boolean isFieldAllFilled) {
        this.isFieldAllFilled = isFieldAllFilled;
    }

    public String getDateDebutCollecte() {
        return dateDebutCollecte;
    }

    public void setDateDebutCollecte(String dateDebutCollecte) {
        this.dateDebutCollecte = dateDebutCollecte;
    }

    public String getDateFinCollecte() {
        return dateFinCollecte;
    }

    public void setDateFinCollecte(String dateFinCollecte) {
        this.dateFinCollecte = dateFinCollecte;
    }

    public Integer getDureeSaisie() {
        return dureeSaisie;
    }

    public void setDureeSaisie(Integer dureeSaisie) {
        this.dureeSaisie = dureeSaisie;
    }

    public String getCodeAgentRecenceur() {
        return codeAgentRecenceur;
    }

    public void setCodeAgentRecenceur(String codeAgentRecenceur) {
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

}
