package ht.ihsi.rgph.mobile.epc.backend.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_individu".
 */
public class Individu {

    private Long individuId;
    private Long menageId;
    private Long logeId;
    private Long batimentId;
    private String sdeId;
    private Short q1NoOrdre;
    private String qp2APrenom;
    private String qp2BNom;
    private Short qp4Sexe;
    private Short q5HabiteDansMenage;
    private Short q6aMembreMenageDepuisQuand;
    private Short q6bDateMembreMenageJour;
    private Short q6bDateMembreMenageMois;
    private Integer q6bDateMembreMenageAnnee;
    private Short q7DateNaissanceJour;
    private Short q7DateNaissanceMois;
    private Integer q7DateNaissanceAnnee;
    private Short q8Age;
    private Short q9LienDeParente;
    private Short q10Nationalite;
    private String q10PaysNationalite;
    private Short q11NiveauEtude;
    private Short q12StatutMatrimonial;
    private Short statut;
    private Boolean isValidated;
    private Boolean isFieldAllFilled;
    private String dateDebutCollecte;
    private String dateFinCollecte;
    private Integer dureeSaisie;
    private Boolean isContreEnqueteMade;
    private String codeAgentRecenceur;
    private Boolean isVerified;

    public Individu() {
    }

    public Individu(Long individuId) {
        this.individuId = individuId;
    }

    public Individu(Long individuId, Long menageId, Long logeId, Long batimentId, String sdeId, Short q1NoOrdre, String qp2APrenom, String qp2BNom, Short qp4Sexe, Short q5HabiteDansMenage, Short q6aMembreMenageDepuisQuand, Short q6bDateMembreMenageJour, Short q6bDateMembreMenageMois, Integer q6bDateMembreMenageAnnee, Short q7DateNaissanceJour, Short q7DateNaissanceMois, Integer q7DateNaissanceAnnee, Short q8Age, Short q9LienDeParente, Short q10Nationalite, String q10PaysNationalite, Short q11NiveauEtude, Short q12StatutMatrimonial, Short statut, Boolean isValidated, Boolean isFieldAllFilled, String dateDebutCollecte, String dateFinCollecte, Integer dureeSaisie, Boolean isContreEnqueteMade, String codeAgentRecenceur, Boolean isVerified) {
        this.individuId = individuId;
        this.menageId = menageId;
        this.logeId = logeId;
        this.batimentId = batimentId;
        this.sdeId = sdeId;
        this.q1NoOrdre = q1NoOrdre;
        this.qp2APrenom = qp2APrenom;
        this.qp2BNom = qp2BNom;
        this.qp4Sexe = qp4Sexe;
        this.q5HabiteDansMenage = q5HabiteDansMenage;
        this.q6aMembreMenageDepuisQuand = q6aMembreMenageDepuisQuand;
        this.q6bDateMembreMenageJour = q6bDateMembreMenageJour;
        this.q6bDateMembreMenageMois = q6bDateMembreMenageMois;
        this.q6bDateMembreMenageAnnee = q6bDateMembreMenageAnnee;
        this.q7DateNaissanceJour = q7DateNaissanceJour;
        this.q7DateNaissanceMois = q7DateNaissanceMois;
        this.q7DateNaissanceAnnee = q7DateNaissanceAnnee;
        this.q8Age = q8Age;
        this.q9LienDeParente = q9LienDeParente;
        this.q10Nationalite = q10Nationalite;
        this.q10PaysNationalite = q10PaysNationalite;
        this.q11NiveauEtude = q11NiveauEtude;
        this.q12StatutMatrimonial = q12StatutMatrimonial;
        this.statut = statut;
        this.isValidated = isValidated;
        this.isFieldAllFilled = isFieldAllFilled;
        this.dateDebutCollecte = dateDebutCollecte;
        this.dateFinCollecte = dateFinCollecte;
        this.dureeSaisie = dureeSaisie;
        this.isContreEnqueteMade = isContreEnqueteMade;
        this.codeAgentRecenceur = codeAgentRecenceur;
        this.isVerified = isVerified;
    }

    public Long getIndividuId() {
        return individuId;
    }

    public void setIndividuId(Long individuId) {
        this.individuId = individuId;
    }

    public Long getMenageId() {
        return menageId;
    }

    public void setMenageId(Long menageId) {
        this.menageId = menageId;
    }

    public Long getLogeId() {
        return logeId;
    }

    public void setLogeId(Long logeId) {
        this.logeId = logeId;
    }

    public Long getBatimentId() {
        return batimentId;
    }

    public void setBatimentId(Long batimentId) {
        this.batimentId = batimentId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public Short getQ1NoOrdre() {
        return q1NoOrdre;
    }

    public void setQ1NoOrdre(Short q1NoOrdre) {
        this.q1NoOrdre = q1NoOrdre;
    }

    public String getQp2APrenom() {
        return qp2APrenom;
    }

    public void setQp2APrenom(String qp2APrenom) {
        this.qp2APrenom = qp2APrenom;
    }

    public String getQp2BNom() {
        return qp2BNom;
    }

    public void setQp2BNom(String qp2BNom) {
        this.qp2BNom = qp2BNom;
    }

    public Short getQp4Sexe() {
        return qp4Sexe;
    }

    public void setQp4Sexe(Short qp4Sexe) {
        this.qp4Sexe = qp4Sexe;
    }

    public Short getQ5HabiteDansMenage() {
        return q5HabiteDansMenage;
    }

    public void setQ5HabiteDansMenage(Short q5HabiteDansMenage) {
        this.q5HabiteDansMenage = q5HabiteDansMenage;
    }

    public Short getQ6aMembreMenageDepuisQuand() {
        return q6aMembreMenageDepuisQuand;
    }

    public void setQ6aMembreMenageDepuisQuand(Short q6aMembreMenageDepuisQuand) {
        this.q6aMembreMenageDepuisQuand = q6aMembreMenageDepuisQuand;
    }

    public Short getQ6bDateMembreMenageJour() {
        return q6bDateMembreMenageJour;
    }

    public void setQ6bDateMembreMenageJour(Short q6bDateMembreMenageJour) {
        this.q6bDateMembreMenageJour = q6bDateMembreMenageJour;
    }

    public Short getQ6bDateMembreMenageMois() {
        return q6bDateMembreMenageMois;
    }

    public void setQ6bDateMembreMenageMois(Short q6bDateMembreMenageMois) {
        this.q6bDateMembreMenageMois = q6bDateMembreMenageMois;
    }

    public Integer getQ6bDateMembreMenageAnnee() {
        return q6bDateMembreMenageAnnee;
    }

    public void setQ6bDateMembreMenageAnnee(Integer q6bDateMembreMenageAnnee) {
        this.q6bDateMembreMenageAnnee = q6bDateMembreMenageAnnee;
    }

    public Short getQ7DateNaissanceJour() {
        return q7DateNaissanceJour;
    }

    public void setQ7DateNaissanceJour(Short q7DateNaissanceJour) {
        this.q7DateNaissanceJour = q7DateNaissanceJour;
    }

    public Short getQ7DateNaissanceMois() {
        return q7DateNaissanceMois;
    }

    public void setQ7DateNaissanceMois(Short q7DateNaissanceMois) {
        this.q7DateNaissanceMois = q7DateNaissanceMois;
    }

    public Integer getQ7DateNaissanceAnnee() {
        return q7DateNaissanceAnnee;
    }

    public void setQ7DateNaissanceAnnee(Integer q7DateNaissanceAnnee) {
        this.q7DateNaissanceAnnee = q7DateNaissanceAnnee;
    }

    public Short getQ8Age() {
        return q8Age;
    }

    public void setQ8Age(Short q8Age) {
        this.q8Age = q8Age;
    }

    public Short getQ9LienDeParente() {
        return q9LienDeParente;
    }

    public void setQ9LienDeParente(Short q9LienDeParente) {
        this.q9LienDeParente = q9LienDeParente;
    }

    public Short getQ10Nationalite() {
        return q10Nationalite;
    }

    public void setQ10Nationalite(Short q10Nationalite) {
        this.q10Nationalite = q10Nationalite;
    }

    public String getQ10PaysNationalite() {
        return q10PaysNationalite;
    }

    public void setQ10PaysNationalite(String q10PaysNationalite) {
        this.q10PaysNationalite = q10PaysNationalite;
    }

    public Short getQ11NiveauEtude() {
        return q11NiveauEtude;
    }

    public void setQ11NiveauEtude(Short q11NiveauEtude) {
        this.q11NiveauEtude = q11NiveauEtude;
    }

    public Short getQ12StatutMatrimonial() {
        return q12StatutMatrimonial;
    }

    public void setQ12StatutMatrimonial(Short q12StatutMatrimonial) {
        this.q12StatutMatrimonial = q12StatutMatrimonial;
    }

    public Short getStatut() {
        return statut;
    }

    public void setStatut(Short statut) {
        this.statut = statut;
    }

    public Boolean getIsValidated() {
        return isValidated;
    }

    public void setIsValidated(Boolean isValidated) {
        this.isValidated = isValidated;
    }

    public Boolean getIsFieldAllFilled() {
        return isFieldAllFilled;
    }

    public void setIsFieldAllFilled(Boolean isFieldAllFilled) {
        this.isFieldAllFilled = isFieldAllFilled;
    }

    public String getDateDebutCollecte() {
        return dateDebutCollecte;
    }

    public void setDateDebutCollecte(String dateDebutCollecte) {
        this.dateDebutCollecte = dateDebutCollecte;
    }

    public String getDateFinCollecte() {
        return dateFinCollecte;
    }

    public void setDateFinCollecte(String dateFinCollecte) {
        this.dateFinCollecte = dateFinCollecte;
    }

    public Integer getDureeSaisie() {
        return dureeSaisie;
    }

    public void setDureeSaisie(Integer dureeSaisie) {
        this.dureeSaisie = dureeSaisie;
    }

    public Boolean getIsContreEnqueteMade() {
        return isContreEnqueteMade;
    }

    public void setIsContreEnqueteMade(Boolean isContreEnqueteMade) {
        this.isContreEnqueteMade = isContreEnqueteMade;
    }

    public String getCodeAgentRecenceur() {
        return codeAgentRecenceur;
    }

    public void setCodeAgentRecenceur(String codeAgentRecenceur) {
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

}
