package ht.ihsi.rgph.mobile.epc.backend.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_logement".
 */
public class Logement {

    private Long logeId;
    private Long batimentId;
    private String sdeId;
    private Short qlCategLogement;
    private Short qlin1NumeroOrdre;
    private Short qlc1TypeLogement;
    private Short qlc2bTotalGarcon;
    private Short qlc2bTotalFille;
    private Short qlcTotalIndividus;
    private Short qlin2StatutOccupation;
    private Short qlin3ExistenceLogement;
    private Short qlin4TypeLogement;
    private Short qlin5MateriauSol;
    private Short qlin6NombrePiece;
    private Short qlin7NbreChambreACoucher;
    private Short qlin8NbreIndividuDepense;
    private Short qlin9NbreTotalMenage;
    private Short statut;
    private Boolean isValidated;
    private String dateDebutCollecte;
    private String dateFinCollecte;
    private Integer dureeSaisie;
    private Boolean isFieldAllFilled;
    private Boolean isContreEnqueteMade;
    private Short nbrTentative;
    private String codeAgentRecenceur;
    private Boolean isVerified;

    public Logement() {
    }

    public Logement(Long logeId) {
        this.logeId = logeId;
    }

    public Logement(Long logeId, Long batimentId, String sdeId, Short qlCategLogement, Short qlin1NumeroOrdre, Short qlc1TypeLogement, Short qlc2bTotalGarcon, Short qlc2bTotalFille, Short qlcTotalIndividus, Short qlin2StatutOccupation, Short qlin3ExistenceLogement, Short qlin4TypeLogement, Short qlin5MateriauSol, Short qlin6NombrePiece, Short qlin7NbreChambreACoucher, Short qlin8NbreIndividuDepense, Short qlin9NbreTotalMenage, Short statut, Boolean isValidated, String dateDebutCollecte, String dateFinCollecte, Integer dureeSaisie, Boolean isFieldAllFilled, Boolean isContreEnqueteMade, Short nbrTentative, String codeAgentRecenceur, Boolean isVerified) {
        this.logeId = logeId;
        this.batimentId = batimentId;
        this.sdeId = sdeId;
        this.qlCategLogement = qlCategLogement;
        this.qlin1NumeroOrdre = qlin1NumeroOrdre;
        this.qlc1TypeLogement = qlc1TypeLogement;
        this.qlc2bTotalGarcon = qlc2bTotalGarcon;
        this.qlc2bTotalFille = qlc2bTotalFille;
        this.qlcTotalIndividus = qlcTotalIndividus;
        this.qlin2StatutOccupation = qlin2StatutOccupation;
        this.qlin3ExistenceLogement = qlin3ExistenceLogement;
        this.qlin4TypeLogement = qlin4TypeLogement;
        this.qlin5MateriauSol = qlin5MateriauSol;
        this.qlin6NombrePiece = qlin6NombrePiece;
        this.qlin7NbreChambreACoucher = qlin7NbreChambreACoucher;
        this.qlin8NbreIndividuDepense = qlin8NbreIndividuDepense;
        this.qlin9NbreTotalMenage = qlin9NbreTotalMenage;
        this.statut = statut;
        this.isValidated = isValidated;
        this.dateDebutCollecte = dateDebutCollecte;
        this.dateFinCollecte = dateFinCollecte;
        this.dureeSaisie = dureeSaisie;
        this.isFieldAllFilled = isFieldAllFilled;
        this.isContreEnqueteMade = isContreEnqueteMade;
        this.nbrTentative = nbrTentative;
        this.codeAgentRecenceur = codeAgentRecenceur;
        this.isVerified = isVerified;
    }

    public Long getLogeId() {
        return logeId;
    }

    public void setLogeId(Long logeId) {
        this.logeId = logeId;
    }

    public Long getBatimentId() {
        return batimentId;
    }

    public void setBatimentId(Long batimentId) {
        this.batimentId = batimentId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public Short getQlCategLogement() {
        return qlCategLogement;
    }

    public void setQlCategLogement(Short qlCategLogement) {
        this.qlCategLogement = qlCategLogement;
    }

    public Short getQlin1NumeroOrdre() {
        return qlin1NumeroOrdre;
    }

    public void setQlin1NumeroOrdre(Short qlin1NumeroOrdre) {
        this.qlin1NumeroOrdre = qlin1NumeroOrdre;
    }

    public Short getQlc1TypeLogement() {
        return qlc1TypeLogement;
    }

    public void setQlc1TypeLogement(Short qlc1TypeLogement) {
        this.qlc1TypeLogement = qlc1TypeLogement;
    }

    public Short getQlc2bTotalGarcon() {
        return qlc2bTotalGarcon;
    }

    public void setQlc2bTotalGarcon(Short qlc2bTotalGarcon) {
        this.qlc2bTotalGarcon = qlc2bTotalGarcon;
    }

    public Short getQlc2bTotalFille() {
        return qlc2bTotalFille;
    }

    public void setQlc2bTotalFille(Short qlc2bTotalFille) {
        this.qlc2bTotalFille = qlc2bTotalFille;
    }

    public Short getQlcTotalIndividus() {
        return qlcTotalIndividus;
    }

    public void setQlcTotalIndividus(Short qlcTotalIndividus) {
        this.qlcTotalIndividus = qlcTotalIndividus;
    }

    public Short getQlin2StatutOccupation() {
        return qlin2StatutOccupation;
    }

    public void setQlin2StatutOccupation(Short qlin2StatutOccupation) {
        this.qlin2StatutOccupation = qlin2StatutOccupation;
    }

    public Short getQlin3ExistenceLogement() {
        return qlin3ExistenceLogement;
    }

    public void setQlin3ExistenceLogement(Short qlin3ExistenceLogement) {
        this.qlin3ExistenceLogement = qlin3ExistenceLogement;
    }

    public Short getQlin4TypeLogement() {
        return qlin4TypeLogement;
    }

    public void setQlin4TypeLogement(Short qlin4TypeLogement) {
        this.qlin4TypeLogement = qlin4TypeLogement;
    }

    public Short getQlin5MateriauSol() {
        return qlin5MateriauSol;
    }

    public void setQlin5MateriauSol(Short qlin5MateriauSol) {
        this.qlin5MateriauSol = qlin5MateriauSol;
    }

    public Short getQlin6NombrePiece() {
        return qlin6NombrePiece;
    }

    public void setQlin6NombrePiece(Short qlin6NombrePiece) {
        this.qlin6NombrePiece = qlin6NombrePiece;
    }

    public Short getQlin7NbreChambreACoucher() {
        return qlin7NbreChambreACoucher;
    }

    public void setQlin7NbreChambreACoucher(Short qlin7NbreChambreACoucher) {
        this.qlin7NbreChambreACoucher = qlin7NbreChambreACoucher;
    }

    public Short getQlin8NbreIndividuDepense() {
        return qlin8NbreIndividuDepense;
    }

    public void setQlin8NbreIndividuDepense(Short qlin8NbreIndividuDepense) {
        this.qlin8NbreIndividuDepense = qlin8NbreIndividuDepense;
    }

    public Short getQlin9NbreTotalMenage() {
        return qlin9NbreTotalMenage;
    }

    public void setQlin9NbreTotalMenage(Short qlin9NbreTotalMenage) {
        this.qlin9NbreTotalMenage = qlin9NbreTotalMenage;
    }

    public Short getStatut() {
        return statut;
    }

    public void setStatut(Short statut) {
        this.statut = statut;
    }

    public Boolean getIsValidated() {
        return isValidated;
    }

    public void setIsValidated(Boolean isValidated) {
        this.isValidated = isValidated;
    }

    public String getDateDebutCollecte() {
        return dateDebutCollecte;
    }

    public void setDateDebutCollecte(String dateDebutCollecte) {
        this.dateDebutCollecte = dateDebutCollecte;
    }

    public String getDateFinCollecte() {
        return dateFinCollecte;
    }

    public void setDateFinCollecte(String dateFinCollecte) {
        this.dateFinCollecte = dateFinCollecte;
    }

    public Integer getDureeSaisie() {
        return dureeSaisie;
    }

    public void setDureeSaisie(Integer dureeSaisie) {
        this.dureeSaisie = dureeSaisie;
    }

    public Boolean getIsFieldAllFilled() {
        return isFieldAllFilled;
    }

    public void setIsFieldAllFilled(Boolean isFieldAllFilled) {
        this.isFieldAllFilled = isFieldAllFilled;
    }

    public Boolean getIsContreEnqueteMade() {
        return isContreEnqueteMade;
    }

    public void setIsContreEnqueteMade(Boolean isContreEnqueteMade) {
        this.isContreEnqueteMade = isContreEnqueteMade;
    }

    public Short getNbrTentative() {
        return nbrTentative;
    }

    public void setNbrTentative(Short nbrTentative) {
        this.nbrTentative = nbrTentative;
    }

    public String getCodeAgentRecenceur() {
        return codeAgentRecenceur;
    }

    public void setCodeAgentRecenceur(String codeAgentRecenceur) {
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

}
