package ht.ihsi.rgph.mobile.epc.backend.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_logement".
 */
public class Logement {

    private Long logeId;
    private Long batimentId;
    private String sdeId;
    private Short qlCategLogement;
    private Short qlin1NumeroOrdre;
    private Short qlin2StatutOccupation;
    private Short qlin3TypeLogement;
    private Short qlin4IsHaveIndividuDepense;
    private Short qlin5NbreTotalMenage;
    private Short statut;
    private Boolean isValidated;
    private Boolean isFieldAllFilled;
    private String dateDebutCollecte;
    private String dateFinCollecte;
    private Integer dureeSaisie;
    private Boolean isContreEnqueteMade;
    private Short nbrTentative;
    private String codeAgentRecenceur;
    private Boolean isVerified;

    public Logement() {
    }

    public Logement(Long logeId) {
        this.logeId = logeId;
    }

    public Logement(Long logeId, Long batimentId, String sdeId, Short qlCategLogement, Short qlin1NumeroOrdre, Short qlin2StatutOccupation, Short qlin3TypeLogement, Short qlin4IsHaveIndividuDepense, Short qlin5NbreTotalMenage, Short statut, Boolean isValidated, Boolean isFieldAllFilled, String dateDebutCollecte, String dateFinCollecte, Integer dureeSaisie, Boolean isContreEnqueteMade, Short nbrTentative, String codeAgentRecenceur, Boolean isVerified) {
        this.logeId = logeId;
        this.batimentId = batimentId;
        this.sdeId = sdeId;
        this.qlCategLogement = qlCategLogement;
        this.qlin1NumeroOrdre = qlin1NumeroOrdre;
        this.qlin2StatutOccupation = qlin2StatutOccupation;
        this.qlin3TypeLogement = qlin3TypeLogement;
        this.qlin4IsHaveIndividuDepense = qlin4IsHaveIndividuDepense;
        this.qlin5NbreTotalMenage = qlin5NbreTotalMenage;
        this.statut = statut;
        this.isValidated = isValidated;
        this.isFieldAllFilled = isFieldAllFilled;
        this.dateDebutCollecte = dateDebutCollecte;
        this.dateFinCollecte = dateFinCollecte;
        this.dureeSaisie = dureeSaisie;
        this.isContreEnqueteMade = isContreEnqueteMade;
        this.nbrTentative = nbrTentative;
        this.codeAgentRecenceur = codeAgentRecenceur;
        this.isVerified = isVerified;
    }

    public Long getLogeId() {
        return logeId;
    }

    public void setLogeId(Long logeId) {
        this.logeId = logeId;
    }

    public Long getBatimentId() {
        return batimentId;
    }

    public void setBatimentId(Long batimentId) {
        this.batimentId = batimentId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public Short getQlCategLogement() {
        return qlCategLogement;
    }

    public void setQlCategLogement(Short qlCategLogement) {
        this.qlCategLogement = qlCategLogement;
    }

    public Short getQlin1NumeroOrdre() {
        return qlin1NumeroOrdre;
    }

    public void setQlin1NumeroOrdre(Short qlin1NumeroOrdre) {
        this.qlin1NumeroOrdre = qlin1NumeroOrdre;
    }

    public Short getQlin2StatutOccupation() {
        return qlin2StatutOccupation;
    }

    public void setQlin2StatutOccupation(Short qlin2StatutOccupation) {
        this.qlin2StatutOccupation = qlin2StatutOccupation;
    }

    public Short getQlin3TypeLogement() {
        return qlin3TypeLogement;
    }

    public void setQlin3TypeLogement(Short qlin3TypeLogement) {
        this.qlin3TypeLogement = qlin3TypeLogement;
    }

    public Short getQlin4IsHaveIndividuDepense() {
        return qlin4IsHaveIndividuDepense;
    }

    public void setQlin4IsHaveIndividuDepense(Short qlin4IsHaveIndividuDepense) {
        this.qlin4IsHaveIndividuDepense = qlin4IsHaveIndividuDepense;
    }

    public Short getQlin5NbreTotalMenage() {
        return qlin5NbreTotalMenage;
    }

    public void setQlin5NbreTotalMenage(Short qlin5NbreTotalMenage) {
        this.qlin5NbreTotalMenage = qlin5NbreTotalMenage;
    }

    public Short getStatut() {
        return statut;
    }

    public void setStatut(Short statut) {
        this.statut = statut;
    }

    public Boolean getIsValidated() {
        return isValidated;
    }

    public void setIsValidated(Boolean isValidated) {
        this.isValidated = isValidated;
    }

    public Boolean getIsFieldAllFilled() {
        return isFieldAllFilled;
    }

    public void setIsFieldAllFilled(Boolean isFieldAllFilled) {
        this.isFieldAllFilled = isFieldAllFilled;
    }

    public String getDateDebutCollecte() {
        return dateDebutCollecte;
    }

    public void setDateDebutCollecte(String dateDebutCollecte) {
        this.dateDebutCollecte = dateDebutCollecte;
    }

    public String getDateFinCollecte() {
        return dateFinCollecte;
    }

    public void setDateFinCollecte(String dateFinCollecte) {
        this.dateFinCollecte = dateFinCollecte;
    }

    public Integer getDureeSaisie() {
        return dureeSaisie;
    }

    public void setDureeSaisie(Integer dureeSaisie) {
        this.dureeSaisie = dureeSaisie;
    }

    public Boolean getIsContreEnqueteMade() {
        return isContreEnqueteMade;
    }

    public void setIsContreEnqueteMade(Boolean isContreEnqueteMade) {
        this.isContreEnqueteMade = isContreEnqueteMade;
    }

    public Short getNbrTentative() {
        return nbrTentative;
    }

    public void setNbrTentative(Short nbrTentative) {
        this.nbrTentative = nbrTentative;
    }

    public String getCodeAgentRecenceur() {
        return codeAgentRecenceur;
    }

    public void setCodeAgentRecenceur(String codeAgentRecenceur) {
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

}
