package ht.ihsi.rgph.mobile.epc.backend.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_menage".
 */
public class Menage {

    private Long menageId;
    private Long logeId;
    private Long batimentId;
    private String sdeId;
    private Short qm1NoOrdre;
    private Short qm2TotalIndividuVivant;
    private Short qm22IsHaveAncienMembre;
    private Short qm22TotalAncienMembre;
    private Short statut;
    private Boolean isValidated;
    private Boolean isFieldAllFilled;
    private String dateDebutCollecte;
    private String dateFinCollecte;
    private Integer dureeSaisie;
    private Boolean isContreEnqueteMade;
    private String codeAgentRecenceur;
    private Boolean isVerified;

    public Menage() {
    }

    public Menage(Long menageId) {
        this.menageId = menageId;
    }

    public Menage(Long menageId, Long logeId, Long batimentId, String sdeId, Short qm1NoOrdre, Short qm2TotalIndividuVivant, Short qm22IsHaveAncienMembre, Short qm22TotalAncienMembre, Short statut, Boolean isValidated, Boolean isFieldAllFilled, String dateDebutCollecte, String dateFinCollecte, Integer dureeSaisie, Boolean isContreEnqueteMade, String codeAgentRecenceur, Boolean isVerified) {
        this.menageId = menageId;
        this.logeId = logeId;
        this.batimentId = batimentId;
        this.sdeId = sdeId;
        this.qm1NoOrdre = qm1NoOrdre;
        this.qm2TotalIndividuVivant = qm2TotalIndividuVivant;
        this.qm22IsHaveAncienMembre = qm22IsHaveAncienMembre;
        this.qm22TotalAncienMembre = qm22TotalAncienMembre;
        this.statut = statut;
        this.isValidated = isValidated;
        this.isFieldAllFilled = isFieldAllFilled;
        this.dateDebutCollecte = dateDebutCollecte;
        this.dateFinCollecte = dateFinCollecte;
        this.dureeSaisie = dureeSaisie;
        this.isContreEnqueteMade = isContreEnqueteMade;
        this.codeAgentRecenceur = codeAgentRecenceur;
        this.isVerified = isVerified;
    }

    public Long getMenageId() {
        return menageId;
    }

    public void setMenageId(Long menageId) {
        this.menageId = menageId;
    }

    public Long getLogeId() {
        return logeId;
    }

    public void setLogeId(Long logeId) {
        this.logeId = logeId;
    }

    public Long getBatimentId() {
        return batimentId;
    }

    public void setBatimentId(Long batimentId) {
        this.batimentId = batimentId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public Short getQm1NoOrdre() {
        return qm1NoOrdre;
    }

    public void setQm1NoOrdre(Short qm1NoOrdre) {
        this.qm1NoOrdre = qm1NoOrdre;
    }

    public Short getQm2TotalIndividuVivant() {
        return qm2TotalIndividuVivant;
    }

    public void setQm2TotalIndividuVivant(Short qm2TotalIndividuVivant) {
        this.qm2TotalIndividuVivant = qm2TotalIndividuVivant;
    }

    public Short getQm22IsHaveAncienMembre() {
        return qm22IsHaveAncienMembre;
    }

    public void setQm22IsHaveAncienMembre(Short qm22IsHaveAncienMembre) {
        this.qm22IsHaveAncienMembre = qm22IsHaveAncienMembre;
    }

    public Short getQm22TotalAncienMembre() {
        return qm22TotalAncienMembre;
    }

    public void setQm22TotalAncienMembre(Short qm22TotalAncienMembre) {
        this.qm22TotalAncienMembre = qm22TotalAncienMembre;
    }

    public Short getStatut() {
        return statut;
    }

    public void setStatut(Short statut) {
        this.statut = statut;
    }

    public Boolean getIsValidated() {
        return isValidated;
    }

    public void setIsValidated(Boolean isValidated) {
        this.isValidated = isValidated;
    }

    public Boolean getIsFieldAllFilled() {
        return isFieldAllFilled;
    }

    public void setIsFieldAllFilled(Boolean isFieldAllFilled) {
        this.isFieldAllFilled = isFieldAllFilled;
    }

    public String getDateDebutCollecte() {
        return dateDebutCollecte;
    }

    public void setDateDebutCollecte(String dateDebutCollecte) {
        this.dateDebutCollecte = dateDebutCollecte;
    }

    public String getDateFinCollecte() {
        return dateFinCollecte;
    }

    public void setDateFinCollecte(String dateFinCollecte) {
        this.dateFinCollecte = dateFinCollecte;
    }

    public Integer getDureeSaisie() {
        return dureeSaisie;
    }

    public void setDureeSaisie(Integer dureeSaisie) {
        this.dureeSaisie = dureeSaisie;
    }

    public Boolean getIsContreEnqueteMade() {
        return isContreEnqueteMade;
    }

    public void setIsContreEnqueteMade(Boolean isContreEnqueteMade) {
        this.isContreEnqueteMade = isContreEnqueteMade;
    }

    public String getCodeAgentRecenceur() {
        return codeAgentRecenceur;
    }

    public void setCodeAgentRecenceur(String codeAgentRecenceur) {
        this.codeAgentRecenceur = codeAgentRecenceur;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

}
