package ht.ihsi.rgph.mobile.epc.backend.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_question_module".
 */
public class QuestionModule {

    private String ordre;
    /** Not-null value. */
    private String codeModule;
    /** Not-null value. */
    private String codeQuestion;
    private Boolean estDebut;

    public QuestionModule() {
    }

    public QuestionModule(String ordre, String codeModule, String codeQuestion, Boolean estDebut) {
        this.ordre = ordre;
        this.codeModule = codeModule;
        this.codeQuestion = codeQuestion;
        this.estDebut = estDebut;
    }

    public String getOrdre() {
        return ordre;
    }

    public void setOrdre(String ordre) {
        this.ordre = ordre;
    }

    /** Not-null value. */
    public String getCodeModule() {
        return codeModule;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodeModule(String codeModule) {
        this.codeModule = codeModule;
    }

    /** Not-null value. */
    public String getCodeQuestion() {
        return codeQuestion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodeQuestion(String codeQuestion) {
        this.codeQuestion = codeQuestion;
    }

    public Boolean getEstDebut() {
        return estDebut;
    }

    public void setEstDebut(Boolean estDebut) {
        this.estDebut = estDebut;
    }

}
